- README.md
#24 Since we require that `coverage`, `dart_style`, and `test` be immediate dependencies so that we can run their executables, we should add those to the install instructions in the readme.
- Update recommended dart_dev version to "^1.0.0" in anticipation of first release
- Require `coverage` "^0.7.2" since that is the first version that supports the `--report-on` flag
- Require `dart_style` "^0.2.0" since that is the latest minor version
- Require `test` "^0.12.0" since that is the test runner that our test/coverage tasks were built on
- n/a
- n/a
@jayudey-wf
> CP-847 Add all required dependencies to install instructions

- .travis.yml
- README.md
- lib/src/tasks/coverage/api.dart
- lib/src/tasks/coverage/cli.dart
- lib/src/tasks/test/api.dart
- lib/src/tasks/test/cli.dart
- lib/src/tasks/test/config.dart
- lib/src/util.dart
- lib/util.dart
- test/integration/copy_license_test.dart
- test/integration/coverage_test.dart
- test/integration/format_test.dart
- tool/dev.dart
#29 Setup CI build through Travis CI
**Source:**
- Add `.travis.yml`
- Add travis badge to readme
- Add a `--concurrency` option to the Test task (simply forwarded to the `test` package executable)
- Use the `path` package to properly join paths (many paths erroneously included double slashes `//`)\
- Add a check to ensure the `coverage.lcov` file was properly created
- Listen to content-shell's stdout for the observatory port in addition to stderr - I noticed on a few Travis builds that the observatory port output to stderr was malformed, so watching both should catch the correct one
- Don't try to open the report if the `--no-html` option was set, because there would be no report to open
- Add a utility to copy a directory and its contents using Dart's File API instead of using an OS …
> CP-858 Travis CI, dart_dev

- .travis.yml
- README.md
_Dependent on #39._
#30 Setup codecov.io reporting.
- Add bash reporter step to travis CI build.
- Add codecov.io badge to readme
- n/a
- CI build runs and passes and the codecov bash reporter successfully found the `coverage.lcov` file and uploaded it to codecov.io (build logs should indicate this).
- Codecov report should show up here: https://codecov.io/github/Workiva/dart_dev
@jayudey-wf
> CP-859 Codecov.io, dart_dev

- lib/src/dart_dev_cli.dart
When a project has a custom `tool/dev.dart` configuration, dart_dev has to spawn a process to take advantage of that. Dart_dev then waits for that process to complete before exiting the main process. It's possible that this sub process may fail to complete, even if the dart_dev task has completed successfully.
**Source:**
- The `dev()` file that acts as the entry point for the executable (either through the default usage or through the sub-process scenario that runs a project's `tool/dev.dart` file) now explicitly exits the process to force completion of the parent task.
**Tests:**
- n/a
- n/a
- CI build passes.
@jayudey-wf
> CP-864 Explicitly exit process when dart_dev has finished

- .gitignore
- README.md
- lib/src/platform_util/api.dart
- lib/src/platform_util/mock_platform_util.dart
- lib/src/platform_util/platform_util.dart
- lib/src/platform_util/standard_platform_util.dart
- lib/src/tasks/coverage/api.dart
- lib/src/tasks/coverage/cli.dart
- lib/src/tasks/coverage/exceptions.dart
- lib/src/tasks/format/cli.dart
- lib/src/tasks/test/cli.dart
- lib/src/util.dart
- lib/util.dart
- test/integration/coverage_test.dart
#42 Generating an HTML report for coverage collection requires that "lcov" is installed. Currently, if that dependency is missing, the coverage task will fail with an non-helpful message when trying to generate the HTML report.
**Source:**
- Introduce the concept of "platform utils"
- Utility methods for interacting with the state of the current project or platform
- Built to allow mocking
- `hasImmediateDependency`, `isExecutableInstalled`
- Use `isExecutableInstalled` util to determine if "lcov" is installed
- if not, API throw a descriptive exception before even running the coverage task to save time
- CLI updated to catch this exception and display the helpful message to stderr
- Some general cleanup of the coverage task
- Create descriptive exception classes
- Consolidate the …
> CP-907 Coverage: check for lcov dependency, fail helpfully

- .gitignore
- README.md
- lib/src/dart_dev_cli.dart
- lib/src/platform_util/api.dart
- lib/src/platform_util/mock_platform_util.dart
- lib/src/platform_util/platform_util.dart
- lib/src/platform_util/standard_platform_util.dart
- lib/src/tasks/config.dart
- lib/src/tasks/coverage/exceptions.dart
- lib/src/tasks/docs/api.dart
- lib/src/tasks/docs/cli.dart
- lib/src/tasks/docs/config.dart
- lib/src/tasks/init/api.dart
- pubspec.yaml
- test/fixtures/docs/docs/lib/main.dart
- test/fixtures/docs/docs/pubspec.yaml
- test/fixtures/docs/no_dartdoc_package/pubspec.yaml
- test/integration/docs_test.dart
#26 To round out the suite of tasks available, documentation generation should be included.
**Source:**
- Add a **docs** task that uses [dartdoc](https://github.com/dart-lang/dartdoc) to generate documentation
- The defaults for documentation generation should be fairly standard, so for now, there are no configuration options
- The CLI has an `--open` flag that defaults to true but can be negated. This flag controls whether or not the generated docs should be opened automatically.
**Tests:**
- Two integration tests added for the docs task.
- n/a
- Verify that the docs task successfully generates and opens documentation
- `ddev docs`
- `doc/api/` created
- `doc/api/index.html` opened automatically in browser
- Verify that the docs are not opened automatically when `--no-open` is set
- …
> CP-924 New Task: documentation generation via dartdoc.

- lib/src/tasks/coverage/cli.dart
#59 
**Source:**
- Need to add an `await` when running the "open" command after generating coverage report
**Tests:**
- n/a
- n/a
- This is sort of hard to test, but on master you should see inconsistent behavior on whether or not the coverage report is automatically opened after generation.
- With this change, the report should always open (as long as `--open` flag is set to true)
@jayudey-wf
> CP-925 Coverage: wait for "open" command

- .gitignore
- lib/src/tasks/examples/api.dart
- lib/src/tasks/examples/cli.dart
Fix #52
Currently if `pub serve` has any output on stderr during the examples task, it will cause the dart_dev process to exit. This happens any time there is a dart2js warning, or even a 404 (even for favicon.ico!)
**Source:**
- Expose additional output stream for pubServeStdErr from ExamplesTask
- Log pubSeveStdErr as the error stream, making it yellow. Screenshot:
- None, bugfix only.
- Target this version of dart_dev in some project that uses it and has examples
- Run `pub run dart_dev examples`
- In the browser, cause a 404. A force refresh would request the favicon.ico, for example.
- Pub serve should continue running after the 404, and the 404 should show up as yellow in the console like the screenshot above.
@trentgrover-wf 
FYI @jayudey-wf
> CP-958 Prevent pub serve errors from examples task

- README.md
- pubspec.yaml
- test/fixtures/format/changes_needed/pubspec.yaml
- test/fixtures/format/no_changes_needed/pubspec.yaml
Resolves #67. `dart_style` range is too narrow and causes dependency version conflicts when installed next to many other projects.
- Update the pubspec.yaml to accept any dart_style version within `>=0.1.8 <0.3.0`
- Update the test fixtures accordingly
- Update the install instructions in the readme
- Installation in other projects
- CI passes.
- Try installing this branch of dart_dev along with web-skin-dart and ensure that no conflicts arise during installation.
@jayudey-wf
> CP-960 Widen dart_style range to include ^0.1.8

- CHANGELOG.md
- README.md
- The readme has several formatting errors when rendered on pub.dartlang.org (#48)
- The changelog is missing the updates that have been merged since 1.0.0
- Updated README for better rendering on pub.dartlang.org (resolves #48)
- Added missing info to CHANGELOG
> Displaying the "rich diff" for these files will be helpful since I changed the line length throughout the README and I switched to HTML tables from GitHub's simpler table syntax.
n/a
n/a - we can't really determine how this will look on pub.dartlang.org until it's published there.
@jayudey-wf
> CP-961 Fix formatting of README, update CHANGELOG

- lib/src/tasks/coverage/api.dart
#45 
**Source:**
- Delete the entire `collections/` directory that holds the temporary collection files after they have been read and merged.
**Tests:**
- n/a
- coverage
- on master:
- `ddev coverage --integration`
- verify that temp file in `coverage/collections/` was not deleted
- on this branch
- `ddev coverage --integration`
- verify that temp directory `coverage/collections/` was deleted entirely
@jayudey-wf
> CP-962 Delete first temporary coverage file.

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-868
CP-958  - Prevent pub serve errors from examples task  - https://github.com/Workiva/dart_dev/pull/68
CP-960  - Widen dart_style range to include ^0.1.8  - https://github.com/Workiva/dart_dev/pull/69
CP-961  - Fix formatting of README, update CHANGELOG  - https://github.com/Workiva/dart_dev/pull/70
CP-962  - Delete first temporary coverage file.  - https://github.com/Workiva/dart_dev/pull/71
CP-917  - Add pub badge to readme.  - https://github.com/Workiva/dart_dev/pull/56
CP-907  - Coverage: check for lcov dependency, fail helpfully  - https://github.com/Workiva/dart_dev/pull/53
CP-924  - New Task: documentation generation via dartdoc.  - https://github.com/Workiva/dart_dev/pull/58
CP-925  - Coverage: …
> CP-868 Release dart_dev 1.0.1

- .gitignore
- lib/src/tasks/coverage/api.dart
- test/fixtures/coverage/non_test_file/lib/non_test_file.dart
- test/fixtures/coverage/non_test_file/pubspec.yaml
- test/fixtures/coverage/non_test_file/test/file.dart
- test/fixtures/coverage/non_test_file/tool/dev.dart
- test/integration/coverage_test.dart
- #76
**Source:**
- Updated file check to just verify that file being passed in is a `.dart` file
**Tests:**
- Added test to verify updated functionality
- Coverage
- Passing CI
- That coverage will work when a non_test dart file is specified.
@evanweible-wf
> CP-1063 Running coverage on non_test dart files

- lib/src/tasks/copy_license/api.dart
- test/fixtures/copy_license/license_with_empty_lines/LICENSE
- test/fixtures/copy_license/license_with_empty_lines/lib/main.dart
- test/fixtures/copy_license/license_with_empty_lines/pubspec.yaml
- test/integration/copy_license_test.dart
#75 
**Source:**
- Copy License API now strips off empty lines from the beginning or end of the license contents before applying them to files. Addresses #75.
**Tests:**
- Added an integration test to test this functionality.
- Copy License task
- Integration tests pass.
@jayudey-wf
> CP-1069 Copy License: trim leading/trailing empty lines

- lib/src/tasks/format/api.dart
- lib/src/tasks/format/cli.dart
- lib/src/tasks/format/config.dart
- test/fixtures/format/exclusions/lib/clean.dart
- test/fixtures/format/exclusions/lib/main.dart
- test/fixtures/format/exclusions/pubspec.yaml
- test/fixtures/format/exclusions/tool/dev.dart
- test/integration/format_test.dart
- Addresses #66 
**Source:**
- Format config now has an `exclude` option that takes a list of string paths (directories, files, or both)
- If exclusions are specified, the list of files to format will be expanded manually (instead of letting dartfmt do it) and will skip any file that matches one of the given exclusion paths
- The CLI output will include a warning that lists all files that were excluded from being formatted
**Tests:**
- Integration test added to verify that an unclean file that is excluded does not get formatted
- Format task
- Integration tests pass
- Play around with different values in the `exclude` list and verify that the files you'd expect to be excluded are indeed skipped
@jayudey-wf 
fyi: @aaronlademann-wf …
> CP-1070 Format: allow exclusions

- README.md
For consideration:
@trentgrover-wf @evanweible-wf @maxwellpeterson-wf @jayudey-wf
> CP-1081 Update README with warning about supported platforms on CI servers.

- README.md
- lib/src/tasks/test/cli.dart
- test/integration/test_test.dart
<h3>FOR YOUR CONSIDERATION</h3>
<p>While developing, I like to run the individual test-file that I'm focussed on.  This proposed  change allows us to run one or more specific test-files.
</p>
<p><strong>Example with single test file:</strong></p>
```
ddev test path/to/tests/my_test.dart
```
<p><strong>Example with multiple test files:</strong></p>
```
ddev test path/to/tests/my_test.dart path/to/tests/another_test.dart
```
</p>
<p><strong>Example with integration + specific unit test file(s):</strong></p>
```
ddev test --integration path/to/tests/my_test.dart path/to/tests/another_test.dart
```
</p>
<h4>Preserved Functionality</h4>
<p><strong>Example with integration tests :</strong></p>
```
ddev test --integration
```
</p>
<p><strong>Example with unit-tests :</strong></p>
```
ddev test …
```
> CP-1091 Allow individual test files

- pubspec.yaml
- test/fixtures/docs/docs/pubspec.yaml
If consumers currently want to use a version of `dartdoc` newer than 0.4.0 alongside dart_dev, they'll need a dependency override
**Source:**
- Relax the `dartdoc` dependency range to include any version between 0.4.0 and 0.9.0
**Tests:**
- Update docs integration test to include the same version range.
- Doc generation
- Integration tests pass
FYI @jayudey-wf
> CP-1102 Upgrade dartdoc dependency range

- lib/src/tasks/coverage/api.dart
- lib/src/tasks/test/api.dart
- test/integration/coverage_test.dart
- The dart2js analyze output that we use to detect whether or not a dart file imports `dart:html` changed from "Error: library not found" to "Error: library not supported"
- Also, the project paths for browser/vm test fixtures were swapped
**Source:**
- Use a regex to detect either the old error message or the new one so that this detection works on pre-1.13 and 1.13
- Fix the project fixture paths
**Tests:**
- Current tests already cover this (which is why our CI started failing)
- Coverage collection on browser tests without a custom HTML file
- CI (which is on 1.13 now) passes
@jayudey-wf
> CP-1124 Fix browser file detection (dart2js output changed)

- lib/src/tasks/format/cli.dart
"You're" was being used instead of "Your" in the sentence "You're Dart code is good to go!"
**Source:**
- Change output message to have correct grammar.
**Tests:**
- No change
- None
- CI Passes
FYI @jayudey-wf
> CP-1125 Fix incorrect grammer in format task output

- CHANGELOG.md
**DOCS ONLY**
- `CHANGELOG.md` is missing the last two releases
- Update changelog
- n/a
- n/a
@jayudey-wf
> CP-1128 Update CHANGELOG with 1.0.3, 1.0.4 releases

- .gitignore
- README.md
- lib/src/reporter.dart
- lib/src/tasks/coverage/api.dart
- lib/src/tasks/coverage/cli.dart
- lib/src/tasks/coverage/config.dart
- lib/src/tasks/serve/api.dart
- lib/src/tasks/test/api.dart
- lib/src/tasks/test/cli.dart
- lib/src/tasks/test/config.dart
- test/fixtures/coverage/browser_needs_pub_serve/lib/coverage_browser.dart
- test/fixtures/coverage/browser_needs_pub_serve/lib/transformer.dart
- test/fixtures/coverage/browser_needs_pub_serve/pubspec.yaml
- test/fixtures/coverage/browser_needs_pub_serve/test/browser_custom_test.dart
- test/fixtures/coverage/browser_needs_pub_serve/test/browser_custom_test.html
- test/fixtures/coverage/browser_needs_pub_serve/test/browser_test.dart
- test/fixtures/coverage/browser_needs_pub_serve/tool/dev.dart
- test/fixtures/test/needs_pub_serve/lib/transformer.dart
- test/fixtures/test/needs_pub_serve/pubspec.yaml
- test/fixtures/test/needs_pub_serve/test/unit_test.dart
- test/fixtures/test/needs_pub_serve/tool/dev.dart
- test/integration/coverage_test.dart
- test/integration/test_test.dart
Tests and coverage currently cannot be run with files served from a Pub server.
See #79.
* Add `PubServeTask`
* Allows creation and management of `pub serve` instances.
* Add `pub-serve` CLI option and `pubServe` config option to test/coverage tasks.
* Automatically spins up a Pub server that is used to run the tests.
* Add integration tests for `dart_dev coverage`/`dart_dev test` in projects that require a Pub server.
Tweak `Reporter.logGroup` code to be more flexible, and indent for multiline Stream events.
* Verify that integration tests for `test`/`coverage` tasks pass.
* Verify that a real consumer package can run `dart_dev test`/`dart_dev coverage` using a pub server.
* E.g., web_skin_dart with transformer code gen: https://ci.webfilings.com/build/417851
* Verify that `pub serve` …
> CP-1129 Add flag to automatically start `pub serve` when running tests/coverage

- README.md
- lib/src/tasks/analyze/api.dart
- lib/src/tasks/analyze/cli.dart
- lib/src/tasks/analyze/config.dart
- test/integration/analyze_test.dart
Potential fix for https://github.com/Workiva/dart_dev/issues/101
@evanweible-wf @maxwellpeterson-wf @trentgrover-wf
> CP-1140 Initial implementation of failing on analyzer hints

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1127
CP-1128  - Update CHANGELOG with 1.0.3, 1.0.4 releases  - https://github.com/Workiva/dart_dev/pull/100
CP-1129  - Add flag to automatically start `pub serve` when running tests/coverage  - https://github.com/Workiva/dart_dev/pull/92
CP-1140  - Initial implementation of failing on analyzer hints  - https://github.com/Workiva/dart_dev/pull/102
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.4...CP-1127_release_1.0.5
> CP-1127 Release dart_dev 1.0.5

- lib/src/tasks/analyze/api.dart
- test/integration/analyze_test.dart
Major facepalm here - dartanalyzer added support for fatal hints without me realizing it.  So I am putting the analyze/api.dart back to how it was and adding the tag if fatalHints are enabled.
@evanweible-wf @maxwellpeterson-wf @trentgrover-wf
> CP-1149 Use dartanalyzer fatal hints instead of post-processing on our own

- README.md
Completion only works on Bash but some people like Zsh!
Add instructions for making the completions work with Zsh.
@evanweible-wf - you might want to test this to be sure it works in real life, I tested it on my local Zsh from Homebrew, but since I don't use Zsh normally I don't actually have a `.zshrc` and such and I just punched everything in at a command line.
> CP-1164 Update readme with zsh instructions for completions.

- lib/src/platform_util/platform_util.dart
- lib/src/task_process.dart
- lib/src/tasks/copy_license/api.dart
- lib/src/tasks/copy_license/cli.dart
- lib/src/tasks/coverage/api.dart
- lib/src/tasks/coverage/cli.dart
- lib/src/tasks/docs/cli.dart
- lib/src/tasks/examples/api.dart
- lib/src/tasks/examples/cli.dart
- lib/src/tasks/format/cli.dart
- lib/src/tasks/test/cli.dart
- test/integration/test_test.dart
- `dart_style` 0.2.1 is out with improved formatting
- Apply newest formatting
- Bump `dart_style` minimum version to 0.2.1
- n/a
- n/a
@jayudey-wf
> CP-1167 Dart formatter updates for dart_dev, dart_style 0.2.1.

- CHANGELOG.md
- README.md
- lib/src/tasks/analyze/api.dart
- lib/src/tasks/analyze/cli.dart
- lib/src/tasks/analyze/config.dart
- test/fixtures/analyze/strong/lib/strong.dart
- test/fixtures/analyze/strong/pubspec.yaml
- test/integration/analyze_test.dart
- Fixes #111 
**Source:**
- Add `strong` option for analyze config
- Add `--strong` flag to analyze CLI
- Add `strong` param to analyze API
**Tests:**
- Integration test for project with static typing issues and `--no-strong`
- Integration test for project with static typing issues and `strong`
- n/a
- CI passes
@jayudey-wf
> Analyze: support strong mode

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1144
CP-1149  - Use dartanalyzer fatal hints instead of post-processing on our own  - https://github.com/Workiva/dart_dev/pull/108
CP-1164  - Update readme with zsh instructions for completions.  - https://github.com/Workiva/dart_dev/pull/109
CP-1167  - Dart formatter updates for dart_dev, dart_style 0.2.1.  - https://github.com/Workiva/dart_dev/pull/110
CP-1172  - Analyze: support strong mode  - https://github.com/Workiva/dart_dev/pull/112
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.5...CP-1144_release_1.0.6
> CP-1144 Release dart_dev 1.0.6

- .gitignore
- lib/src/tasks/coverage/api.dart
- lib/src/tasks/serve/api.dart
- test/fixtures/coverage/failing_test/lib/coverage_failing_test.dart
- test/fixtures/coverage/failing_test/pubspec.yaml
- test/fixtures/coverage/failing_test/test/failing_test.dart
- test/fixtures/coverage/failing_test/test/passing_test.dart
- test/integration/coverage_test.dart
- https://github.com/Workiva/dart_dev/issues/73
**Source:**
- Added flag that gets set if coverage detects a failing test
**Tests:**
- added
- coverage
- passing CI
- verify that coverage passes and fails as expected
@evanweible-wf
> CP-1303 Fail coverage task if a unit tests fails

- README.md
- lib/src/tasks/test/cli.dart
- test/fixtures/analyze/warnings/lib/warnings.dart
- test/fixtures/analyze/warnings/pubspec.yaml
- test/integration/analyze_test.dart
- test/integration/test_test.dart
- https://github.com/Workiva/dart_dev/issues/55 (master currently address part of this by a user being able to add in individual test files)
**Source:**
- added the ability to pass in a test name through the CLI
- updated analyze test due to changes in dart 1.14.0
**Tests:**
- added
- test execution
- `ddev test` works as expected with and without a named test
@evanweible-wf
> CP-1318 Add ability to pass in test name as a parameter to test task

- lib/src/tasks/test/cli.dart
- test/fixtures/test/passingIntegration/pubspec.yaml
- test/fixtures/test/passingIntegration/test/failing_unit_test.dart
- test/fixtures/test/passingIntegration/test/passing_integration_test.dart
- test/fixtures/test/passingIntegration/tool/dev.dart
- test/integration/test_test.dart
- If a user passed in the following command `pub run dart_dev test --no-unit --integration` unit tests were still being run
[11:26 AM] Travis Sanderson: I am on dart_dev 1.0.6 and when I run "pub run dart_dev test --no-unit --integration" it runs my unit tests too, but if I use coverage with the same params it only runs integrations like I want
**Source:**
- removed un-necessary code block overriding cli params
**Tests:**
- updated tests to verify behavior as expected (in the updated tests if unit tests were run it would cause the test task to fail)
- failing CI
- passing CI
@evanweible-wf
> CP-1393 Update test task to observe `--no-unit` flag

- lib/src/tasks/test/cli.dart
- test/fixtures/test/default_unit/lib/passing_unit.dart
- test/fixtures/test/default_unit/pubspec.yaml
- test/fixtures/test/default_unit/tool/dev.dart
- test/integration/test_test.dart
- With inclusion of https://github.com/Workiva/dart_dev/pull/131 the way unit tests were being included wasn't working as expected.
[6:20 PM] Greg Littlefield: FYI Our builds started failing after dart_dev 1.1.0 was released: https://github.com/Workiva/web_skin_dart/pull/284. In case anyone runs into a similar issue.
**Source:**
- Updated the logic to see if the cli param was explicitly set to false
- Updated the tests that runs default unit tests to fail if unit tests aren't being run by default
**Tests:**
- updated
- the `test` task
- verify that `test` task is working as expected
@evanweible-wf
> CP-1398 Update logic around including unit tests by default

- .gitignore
- README.md
- pubspec.yaml
Coverage broke with Dart SDK 1.14. The coverage package released version 0.7.3 to address this issue, although it was only compatible with Dart SDK 1.15. Now that 1.15 is out, we need to update and make sure coverage is working.
Upgrade to coverage 0.7.3.
@trentgrover-wf 
@jayudey-wf
> CP-1453 Upgrade to coverage 0.7.3 to fix coverage issues

- CHANGELOG.md
- lib/src/dart_dev_cli.dart
- lib/src/tasks/analyze/cli.dart
- lib/src/tasks/cli.dart
- lib/src/tasks/copy_license/cli.dart
- lib/src/tasks/coverage/cli.dart
- lib/src/tasks/docs/cli.dart
- lib/src/tasks/examples/cli.dart
- lib/src/tasks/format/cli.dart
- lib/src/tasks/init/cli.dart
- lib/src/tasks/test/cli.dart
- test/fixtures/test/default_unit/test/unit_test.dart
- test/integration/test_test.dart
Fix #137.
Fix #138.
Originally discovered in #138. The test is incorrectly including the default unit test suite even when individual tests are given as args and even with `--no-unit`.
Additionally, the test task does not respect the `--no-color` flag (#137).
- Update the `TaskCli.run` abstract method to take `color` as an optional param. This allows the top-level CLI to pass the value of the `color` flag into the tasks.
- Forward the `--no-color` flag onto the the `pub run test` command.
- Update the logic used to build the list of tests to run as follows:
- If individual test files/directories are passed in, only those are run.
- Unless `--no-unit` is passed in, run the unit test suite.
- If `--integration` is passed in, run the integration suite.
- The tests for the test task have been …
> CP-1480 Test Task: correctly build the set of tests to run and respect the --no-color flag

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1400
CP-1453  - Upgrade to coverage 0.7.3 to fix coverage issues  - https://github.com/Workiva/dart_dev/pull/140
CP-1480  - Test Task correctly build the set of tests to run and respect the nocolor flag  - https://github.com/Workiva/dart_dev/pull/141
CP-1524  - Coverage tests were routinely timing out on travis.ci  - https://github.com/Workiva/dart_dev/pull/143
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.1.1...CP-1400_release_1.1.2
> CP-1400 Release dart_dev 1.1.2

- lib/src/tasks/saucelabs_tests/sauce_unit_test_driver.dart
For some reason, Sauce Labs no longer activates the Firefox window when running tests. In Firefox, if the window isn't active, focus events won't be fired (see <https://bugzilla.mozilla.org/show_bug.cgi?id=566671>).
This causes focus-related unit tests to fail in Firefox for Sauce Labs builds.
_Focusing the iframe, its window and then its body via JS doesn't work._
_Focusing/blurring all kinds of other elements via JS doesn't work._
_Setting the iframe as the active frame in the WebDriver doesn't work._
What does work? Having the WebDriver click the page before it loads our tests, which has the side effect of activating the browser window.
Verify that focus-related tests pass. (see https://github.com/Workiva/web_skin_dart/pull/391)
Sauce Labs builds.
---
FYA: @jayudey-wf 
FYI: …
> Fix Firefox test failures in Sauce Labs due to window not being active

- README.md
- lib/src/tasks/test/cli.dart
- lib/src/util.dart
- lib/util.dart
- test/integration/test_test.dart
This is WIP as I'm not familiar with the expected code approach. Let me know any changes to better implement this sort of feature. I'm open to cleaning it up.
Problem
--
Running tests with `pub serve` is slow due to starting a new pub server for every run. If the pub serve existed as long as I wanted, the tests could speed up by reusing that same serve instance. In my specific case, the test watcher I use on SOX will start/stop the pub serve for me so it is cleaned up.
Solution
--
Allow a `pub-serve-port` arg on the test CLI so it doesn't start pub serve and only passes the port to the test run.
How to test
--
Verify all tests pass.
References
--
* /cc
* @evanweible-wf
* @maxwellpeterson-wf
* @trentgrover-wf
* @georgelesica-wf
> CP-1768 Allow a provided pub serve port

- README.md
- tool/ddev.fish
Completion is only offered for Bash and Zsh,  and [Fish](http://fishshell.com/) is pretty great.
- Add `tool/ddev.fish` with completions for all current ddev commands/options.
- This is more long winded than the Bash/Zsh completion script but it also gives you the abbreviated options and documentation!
- Verify completions work as expected (you will need fish, if using brew: `brew install fish`).
> CP-1754 Add fish completions

- README.md
- lib/bash-completion.sh
- lib/src/dart_dev_cli.dart
- lib/src/tasks/bash_completion/api.dart
- lib/src/tasks/bash_completion/cli.dart
- lib/src/tasks/bash_completion/config.dart
- lib/src/tasks/config.dart
- pubspec.yaml
- tool/ddev-completion.sh
- tool/generate_completions.sh
This addresses #103. I've added basic support for generating the completion file using completions.dart.
See the README for information on how to consume the new completions.
The script even works with custom project-specific tasks because it operates by adding a pseudo command to ddev that effectively introspects its current configuration. This means the script won't actually need updating all that often. In the future we may not even need to store the script, we may just generate it on the fly from completions.dart.
Follow the instructions in the README to get it working. Then make sure it works.
Install globally using `pub global activate -s /path/to/clone` instead of the command in the README since that would just install the release version. Of particular use would be testing in zsh …
> CP-1794 Add completions.dart support

- lib/src/tasks/local/cli.dart
Problem
--------
The reported error when running a local task includes a grammatical mistake.
Solution
--------
Correctly use *an*.
Howto Test/QA
--------------------
> Correct Grammar in Error Statement

- lib/src/tasks/local/cli.dart
- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1531
CP-1604  - Functional Coverage Working For Real I Promise  - https://github.com/Workiva/dart_dev/pull/145
CP-1329  - Create dart test runner generator, dart_dev  - https://github.com/Workiva/dart_dev/pull/124
CP-1768  - Allow a provided pub serve port  - https://github.com/Workiva/dart_dev/pull/153
CP-1754  - Add fish completions  - https://github.com/Workiva/dart_dev/pull/149
CP-1794  - Add completions.dart support  - https://github.com/Workiva/dart_dev/pull/151
CP-1811  - Add Local Task Integrations  - https://github.com/Workiva/dart_dev/pull/150
Diff Between Last Tag and Proposed Release: …
> CP-1531 Release dart_dev 1.2.0

- test/integration/test_test.dart
- There was a race condition that existed where https://github.com/Workiva/dart_dev/blob/master/test/integration/test_test.dart#L152 could start executing before the pub serve process could get set up. This was causing test failures.
**Source:**
- Waited for pub-serve to complete prior to test execution
**Tests:**
- n/a
- Tests failing
- Check out branch locally and verify that tests are still passing, on Travis it appears that for dart 1.16.1 content_shell was not properly installed and is causing failures there (https://travis-ci.org/Workiva/dart_dev/builds/135127265#L872)
> CP-1864 Wait for pub-serve process to complete before test execution

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1816
======= dart_dev 1.3.0 items =======
CP-1835  - Dart dev does not allow undefined arguments for any local task.  - https://github.com/Workiva/dart_dev/pull/158
CP-1864  - Wait for pub-serve process to complete before test execution  - https://github.com/Workiva/dart_dev/pull/161
======= end =======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.2.0...CP-1816_release_1.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.2.0...1.3.0
> CP-1816 Release dart_dev 1.3.0

- .gitignore
- README.md
- lib/src/tasks/gen_test_runner/api.dart
- lib/src/tasks/gen_test_runner/cli.dart
- lib/src/tasks/gen_test_runner/config.dart
- pubspec.yaml
- test/integration/gen_test_runner_test.dart
- test_fixtures/coverage/functional_test/pubspec.yaml
- test_fixtures/gen_test_runner/browser_and_vm/pubspec.yaml
- test_fixtures/gen_test_runner/browser_and_vm/test/browser/browser_test.dart
- test_fixtures/gen_test_runner/browser_and_vm/test/vm/vm_test.dart
- test_fixtures/gen_test_runner/browser_and_vm/tool/dev.dart
- test_fixtures/gen_test_runner/check_fail/pubspec.yaml
- test_fixtures/gen_test_runner/check_fail/test/browser_test.dart
- test_fixtures/gen_test_runner/check_fail/test/generated_runner.dart
- test_fixtures/gen_test_runner/check_fail/tool/dev.dart
- test_fixtures/gen_test_runner/check_pass/pubspec.yaml
- test_fixtures/gen_test_runner/check_pass/test/browser_test.dart
- test_fixtures/gen_test_runner/check_pass/test/generated_runner.dart
- test_fixtures/gen_test_runner/check_pass/tool/dev.dart
- test_fixtures/gen_test_runner/default_config/pubspec.yaml
- test_fixtures/gen_test_runner/default_config/test/browser_test.dart
- test_fixtures/gen_test_runner/default_config/tool/dev.dart
We wanted a simple way to fail our build if the test runner hadn't been regenerated.
Add a `--check` flag to the `gen-test-runner` task, to be consistent with the `format` task.
Link into a Dart project that uses the `gen-test-runner` task and try `ddev gen-test-runner --check`. Then make a change, either add a test file, or just make a random change within the generated test runner itself, and run it again.
@evanweible-wf
> REF-956: Add --check option to gen-test-runner task

- pubspec.yaml
The only breaking change in the dartdoc 0.9.0 was an updated SDK constraint, so we should be able to safely include 0.9.x.
@evanweible-wf @maxwellpeterson-wf @trentgrover-wf
> CP-2273 Widen dartdoc version constraint

- lib/src/tools/selenium.dart
- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-2035
======= dart_dev 1.4.1 items =======
CP-2273  - Widen dartdoc version constraint  - https://github.com/Workiva/dart_dev/pull/166
======= end =======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.4.0...CP-2035_release_1.4.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.4.0...1.4.1
> CP-2035 Release dart_dev 1.4.1

- .analysis_options
- lib/src/tasks/gen_test_runner/api.dart
@theisensanders-wf noted that we were adding an extra slash to the runner path. I figured we might as well fix it. I also added an `.analysis_options` file so I could exclude the test fixtures in Atom.
> CP-2388 Fix slash bug

- lib/src/tasks/gen_test_runner/api.dart
- lib/src/tasks/gen_test_runner/cli.dart
- lib/src/tools/selenium.dart
It seems that while `gen-test-runner --check` works locally, it fails on Smithy, at least some of the time. I suspect that the directory listing order just isn't stable across platforms. Sorting the test files fixes the problem. I also added some more helpful error output. @evanweible-wf @maxwellpeterson-wf
> CP-2404 Fix bug when gen-test-runner --check runs on Smithy

- pubspec.yaml
* [CP-2388 Fix slash bug](https://github.com/Workiva/dart_dev/pull/168)
* [CP-2404 Fix bug when gen-test-runner --check runs on Smithy](https://github.com/Workiva/dart_dev/pull/169)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.4.1...version-bump-dart_dev-1-4-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.4.1...1.4.2
> CP-2383 Release dart_dev 1.4.2

- pubspec.yaml
* [CP-2272 Implemented task that allows a user to run browser based dart unit tests on saucelabs](https://github.com/Workiva/dart_dev/pull/148)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.4.2...version-bump-dart_dev-1-5-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.4.2...1.5.0
> CP-2661 Release dart_dev 1.5.0

- README.md
Add a link to the 2.0.0-alpha release in the readme to help people who are visiting this repo directly.
**Don't merge this until 2.0.0-alpha has been released.**
@trentgrover-wf 
@jayudey-wf 
@sebastianmalysa-wf
> Link to 2.0.0-alpha

- pubspec.yaml
* [CP-2824 Fixes for compatibility with Dart 1.20.x](https://github.com/Workiva/dart_dev/pull/183)
* [CP-2858 Update gen-test-runner task based on feedback](https://github.com/Workiva/dart_dev/pull/184)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.0...version-bump-dart_dev-1-5-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.0...1.5.1
> CP-2767 Release dart_dev 1.5.1

- smithy.yaml
- We needed to add a smithy.yaml for release management to more easily track dependencies.
**Source:**
- Included smithy.yaml
**Tests:**
- n/a
- passing CI's
- passing CI
@evanweible-wf
@sebastianmalysa-wf
> CP-2946 Adding smithy.yaml

- lib/src/tasks/analyze/api.dart
- lib/src/tasks/analyze/cli.dart
- lib/src/tasks/analyze/config.dart
- test/integration/analyze_test.dart
- test_fixtures/analyze/lints/.analysis_options
- test_fixtures/analyze/lints/lib/hints.dart
- test_fixtures/analyze/lints/lib/lints.dart
- test_fixtures/analyze/lints/pubspec.yaml
Addresses https://github.com/Workiva/dart_dev/issues/164
@evanweible-wf @maxwellpeterson-wf @trentgrover-wf @jayudey-wf
> CP-2275 Adds support for --fatal-lints analyzer flag

- pubspec.yaml
* [CP-2275 Adds support for --fatal-lints analyzer flag](https://github.com/Workiva/dart_dev/pull/190)
* [CP-2946 Adding smithy.yaml](https://github.com/Workiva/dart_dev/pull/191)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.1...version-bump-dart_dev-1-5-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.1...1.5.2
> CP-2861 Release dart_dev 1.5.2

- README.md
Following the existing dart_dev documentation, users will not be able to pull down the latest version of dart_dev
Tweak the dependencies in the documentation
Make a new project with a new `pubspec.yaml`. Add the listed dependencies and run `pub get`. Verify that dart_dev 1.5.2 is pulled down.
@evanweible-wf
@jayudey-wf
> CP-2990 Fix README dependencies so that users can pull down the latest dart_dev

- lib/src/tasks/local/config.dart
[Jira Ticket](https://jira.atl.workiva.net/browse/RAP-1367)
It would be nice to be able to name local tasks using the convention followed by the built-in tasks whereby multi-word commands are separated by a hyphen. Right now we only accept alphanumeric names.
Add a hyphen to the regex.
None.
NA - untested
1. Checkout the branch.
2. Update dependencies.
3. Unit tests should pass.
4. Pull this branch into the "Home" application (repo: home).
5. Rename the file `tool/tasks/watchsass_task.dart` to `tool/tasks/watch-sass_task.dart`.
6. Run `ddev watch-sass`, this should work.
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp
> RAP-1367 Add hyphen to local task regex

- pubspec.yaml
* [CP-2990 Fix README dependencies so that users can pull down the latest dart_dev](https://github.com/Workiva/dart_dev/pull/194)
* [RAP-1367 Add hyphen to local task regex](https://github.com/Workiva/dart_dev/pull/196)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.2...version-bump-dart_dev-1-5-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.2...1.5.3
> CP-2954 Release dart_dev 1.5.3

- README.md
- lib/src/dart_dev_cli.dart
- lib/src/tasks/coverage/cli.dart
- lib/src/tasks/coverage/config.dart
- lib/src/tasks/test/cli.dart
- lib/src/tasks/test/config.dart
- lib/src/util.dart
- lib/util.dart
- test_fixtures/coverage/functional_test/tool/dev.dart
- There were issues trying to set up the before and after commands needed for the functional tasks that wouldn't negatively impact other tasks.
**Source:**
- Added the ability to specify tasks to be run exclusively before functional tasks.
**Tests:**
- updated
- functional coverage / testing
- before and after commands for other tasks
- CI
- install into a project and ensure that newly added (and historical) functionality is working as expected
@Workiva/web-platform-pp 
@joewaters-wf
> Add additional configuration options to functional coverage / test task

- .travis.yml
- README.md
- lib/src/dart_dev_cli.dart
- lib/src/tasks/config.dart
- lib/src/tasks/task_runner/api.dart
- lib/src/tasks/task_runner/cli.dart
- lib/src/tasks/task_runner/config.dart
- test/integration/generated_runner.dart
- test/integration/task_runner_test.dart
- test_fixtures/task_runner/failing_tasks/lib/main.dart
- test_fixtures/task_runner/failing_tasks/pubspec.yaml
- test_fixtures/task_runner/failing_tasks/test/simple_test.dart
- test_fixtures/task_runner/failing_tasks/tool/dev.dart
- test_fixtures/task_runner/passing_tasks/lib/main.dart
- test_fixtures/task_runner/passing_tasks/pubspec.yaml
- test_fixtures/task_runner/passing_tasks/test/simple_test.dart
- test_fixtures/task_runner/passing_tasks/tool/dev.dart
- There is no way to easily run dart tasks asynchronously.
**Source:**
- Created a task to allow for a user to specify dart commands that they wish to run in parallel.
**Tests:**
- added
- n/a (new tasks was added)
- passing CI
- install into this branch into a repo and ensure that the tasks complete as expected (I tried doing this on travis CI for dart_dev and I don't think the instance could handle running the tasks)
> CP-3183 Create dart_dev task to allow for tasks to run con-currently

- pubspec.yaml
* [CP-3183 Create dart_dev task to allow for tasks to run con-currently](https://github.com/Workiva/dart_dev/pull/199)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.6.0...version-bump-dart_dev-1-7-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.6.0...1.7.0
> CP-3325 Release dart_dev 1.7.0

- .gitignore
- lib/src/reporter.dart
- lib/src/tasks/test/api.dart
The Reporter logGroup has an outputStream and errorStream.  Many tasks just use the outputStream and add errors on to that stream.  The outputStream does not have an onError handler.  When any errors are added, they cause a useless exception, and the user can't see what actually went wrong.
Add onError handlers.
> HY-4464 - Add onError handlers to Reporter

- lib/src/tasks/coverage/api.dart
Hello. This merge request changes coverage/api.dart so it uses single ```pub serve``` instance to run browser tests (if any) instead of starting and killing ```pub serve``` for each test. This reduces running time almost twice.
> CP-3485 Pub serve single instance for coverage

- lib/src/tasks/format/api.dart
- test/integration/format_test.dart
- test_fixtures/format/exclusions/lib/.pub/main.dart
- test_fixtures/format/exclusions/lib/packages/main.dart
When you specify a set of files to be excluded during formatting dart_dev walks the file structure and identifies each file that should be formatted. Currently it is picking up files in `.pub` folders. `dartfmt` skips those folders, so `ddev format` should too.
Updated the format task to skip folders named `.pub`.
> RAP-1618 Skip files in .pub directories when formatting

- pubspec.yaml
* [CP-3485 Pub serve single instance for coverage](https://github.com/Workiva/dart_dev/pull/212)
* [RAP-1618 Skip files in .pub directories when formatting](https://github.com/Workiva/dart_dev/pull/213)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.1...version-bump-dart_dev-1-7-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.1...1.7.2
> CP-3445 Release dart_dev 1.7.2

- lib/src/tasks/format/api.dart
- pubspec.yaml
`dart_style` recently jumped to the 1.x line, which our current constraint does not allow. This prevents consumers from upgrading even though our format task is still compatible with the latest.
Widen the `dart_style` range to include 1.x
> WP-3881 Widen dart_style range to include 1.x

- pubspec.yaml
* [WP-3669 : added docs.yml](https://github.com/Workiva/dart_dev/pull/216)
* [WP-3881 Widen dart_style range to include 1.x](https://github.com/Workiva/dart_dev/pull/218)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.2...version-bump-dart_dev-1-7-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.2...1.7.3
> WP-3489 Release dart_dev 1.7.3

- lib/src/dart_dev_cli.dart
- lib/src/tasks/saucelabs/cli.dart
- lib/src/tasks/saucelabs/sauce_iframe_runner/sauce_iframe_runner.dart
- pubspec.yaml
`platform_detect` is strong-mode compliant while `browser_detect` is not.
`platform_detect` intends to replace `browser_detect`.
- Use `platform_detect` instead of `browser_detect`.
- Remove some unused imports.
- CI Passes
> WP-4263 Use platform_detect instead of browser_detect

- pubspec.yaml
* [WP-4263 Use platform_detect instead of browser_detect](https://github.com/Workiva/dart_dev/pull/221)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.4...version-bump-dart_dev-1-7-5
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.4...1.7.5
> WP-4208 Release dart_dev 1.7.5

- .travis.yml
- pubspec.yaml
> WP-4404 Loosen dartdoc range

- pubspec.yaml
* [WP-4404 Loosen dartdoc range](https://github.com/Workiva/dart_dev/pull/225)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.6...version-bump-dart_dev-1-7-7
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.6...1.7.7
> WP-4339 Release dart_dev 1.7.7

- lib/src/tasks/saucelabs/sauce_iframe_runner/sauce_iframe_runner.dart
- pubspec.yaml
- smithy.yaml
- test/integration/task_runner_test.dart
The `rate_limit` package is not strong mode compatible.
Use `rxdart` instead.
@Workiva/rich-app-platform-pp
> RAP-2072 Remove rate_limit dependency.

- .travis.yml
- README.md
- lib/src/sauce_test_harness_transformer.dart
- pubspec.yaml
- test/integration/analyze_test.dart
- test/integration/format_test.dart
We have a few dependencies listed in the `dependencies` section that are only there for their executables. Consumers _have_ to add those dependencies to their `pubspec.yaml` anyway in order to run their executables, so this is unnecessary and as a result, consumers may experience some version lock that would otherwise be avoidable.
Move `coverage`, `dart_style`, `dartdoc`, and `test` from the main dependencies list to the dev dependencies list. Additionally, the readme has been updated to reflect the currently supported version ranges for these executables required by the dart_dev tasks that use them.
- `ddev coverage`
- `ddev format`
- `ddev docs`
- `ddev test`
> WP-4726 Move executable-only deps to dev_deps

- lib/src/tasks/task_runner/api.dart
- pubspec.yaml
- test/integration/task_runner_test.dart
- test_fixtures/task_runner/failing_tasks/test/simple_test.dart
- test_fixtures/task_runner/passing_tasks/test/simple_test.dart
We are seeing the task-runner tests fail intermittently because the test task output is incomplete (it does not include the "All tests passed." or "Some tests failed." line that the test is looking for). I haven't been able to reproduce this locally.
My best guess is that the task runner is considering the tasks done before the stdout/stderr streams have been completely processed due to it listening to the `exitCode` future instead of `done`.
Additionally, there were two dependencies that are being used but aren't explicitly depended on, so I've added those.
> WP-4746 Ensure task runner waits for stdout/stderr before considering task "done"

- pubspec.yaml
* [RAP-2072 Remove rate_limit dependency.](https://github.com/Workiva/dart_dev/pull/228)
* [WP-4726 Move executable-only deps to dev_deps](https://github.com/Workiva/dart_dev/pull/229)
* [WP-4746 Ensure task runner waits for stdout/stderr before considering task "done"](https://github.com/Workiva/dart_dev/pull/231)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.7...version-bump-dart_dev-1-7-8_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.7...1.7.8
> WP-4409 Release dart_dev 1.7.8

- lib/src/tasks/test/cli.dart
- test/integration/test_test.dart
- There was no way to run tests with the dart dev compiler (or really any web-compiler).
**Source:**
- Added a pass through flag that allowed the web-compiler to be specified for the test task.
**Tests:**
- added
- failing tests
- passing CI
- install locally and verify that passing in a flag to the `test` task appropriately updates the serve task
@Workiva/web-platform-pp 
@Workiva/ui-platform-pp
> WP-4898 Allow web-compiler flag to be passed through dart_dev to test task

- .travis.yml
- pubspec.yaml
* [WP-4898 Allow web-compiler flag to be passed through dart_dev to test task](https://github.com/Workiva/dart_dev/pull/235)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.8...version-bump-dart_dev-1-8-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.8...1.8.0
> WP-4762 Release dart_dev 1.8.0

- .travis.yml
- pubspec.yaml
Pretty self-explanatory.  There is no usage of the `sass` package in this repo.
@Workiva/web-platform-pp @Workiva/ui-platform-pp
> WP-5353 Remove unnecessary dependency on sass package

- pubspec.yaml
* [WP-5353 Remove unnecessary dependency on sass package](https://github.com/Workiva/dart_dev/pull/238)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...Workiva:release_dart_dev_1_8_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...1.8.1
> WP-4905 Release dart_dev 1.8.1

- pubspec.yaml
> Upgrade rxdart

- lib/src/tasks/coverage/api.dart
- It was pointed out that there was an inconsistency in the content_shell window size between the test and coverage task.
**Source:**
- Update the content_shell window size in the coverage task to match the window size in the test task.
**Tests:**
- n/a, contant update
- Coverage task
- passing CI
@Workiva/web-platform-pp 
fyi: @aaronlademann-wf
> Update content_shell window size in coverage task

- pubspec.yaml
* [Upgrade rxdart](https://github.com/Workiva/dart_dev/pull/240)
* [Update content_shell window size in coverage task](https://github.com/Workiva/dart_dev/pull/241)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...Workiva:release_dart_dev_1_8_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...1.8.2
> WP-5356 Release dart_dev 1.8.2

- README.md
- lib/src/tasks/gen_test_runner/api.dart
- lib/src/tasks/gen_test_runner/config.dart
- test/integration/gen_test_runner_test.dart
- test_fixtures/gen_test_runner/browser_and_vm_runner/pubspec.yaml
- test_fixtures/gen_test_runner/browser_and_vm_runner/test/browser/browser_test.dart
- test_fixtures/gen_test_runner/browser_and_vm_runner/test/vm/vm_test.dart
- test_fixtures/gen_test_runner/browser_and_vm_runner/tool/dev.dart
- There was no way to specify both `vm` and `browser` in a generated runner file.
**Source:**
- Added an additional platform option.
**Tests:**
- added
- gen-test-runner platform configuration and html generation
- verify that tests work as exists
@Workiva/ui-platform-pp @Workiva/web-platform-pp
> Add ability to create testOn annotation with vm and browser

- pubspec.yaml
* [Add ability to create testOn annotation with vm and browser](https://github.com/Workiva/dart_dev/pull/243)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...Workiva:release_dart_dev_1_9_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...1.9.0
> WP-5475 Release dart_dev 1.9.0

- pubspec.yaml
The latest release of rxdart (0.15.1) fully supports DDC compilation. Widening this range allows all of Workiva to get this latest version. Most repos are stuck at ^0.12.0. The rxdart API is unchanged, so it should be an easy upgrade and rollout.
```
dependency_overrides:
rxdart: 0.15.1
```
> WP-6076 widen rxdart dependency range

- lib/src/tasks/coverage/config.dart
I didn't add any for after/before functional tests yet because those aren't in the README either.
> Add docstrings to coverage config

- Dockerfile
The dockerfile builds are failing because they had fallen behind smithy.yaml while that pr was open
> Update Dockerfile to mirror recent changes to smithy.yaml

- lib/src/task_process.dart
- lib/src/tasks/coverage/api.dart
- lib/src/tasks/test/api.dart
- lib/src/util.dart
Dartium has hit its built-in expiration date, and cannot run Dart code properly unless the date is overridden using the `DARTIUM_EXPIRATION_TIME` environment variable.
https://github.com/dart-lang/sdk/issues/33580
This causes tests and coverage to timeout inexplicably when running content-shell, and only with a popup warning when running in Dartium.
Automatically set this flag in relevant processes launched by dart_dev to work around this issue and prevent frustrating content-shell failures.
- Run `ddev test`/`ddev coverage` in a terminal where `DARTIUM_EXPIRATION_TIME` is unset, and verify that tests pass
> Automatically extend the Dartium expiration date for test/coverage tasks

- pubspec.yaml
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/dart_dev/pull/253)
* [Update Dockerfile to mirror recent changes to smithy.yaml](https://github.com/Workiva/dart_dev/pull/256)
* [Use dependency_validator](https://github.com/Workiva/dart_dev/pull/257)
* [Automatically extend the Dartium expiration date for test/coverage tasks](https://github.com/Workiva/dart_dev/pull/266)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.9.2...Workiva:release_dart_dev_1_9_3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.9.2...1.9.3
The logs for the request that created this PR can be found …
> WP-6447 Release dart_dev 1.9.3

- pubspec.yaml
* [AF-1870 Widen uuid range for Dart 2](https://github.com/Workiva/dart_dev/pull/269)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.9.4...Workiva:release_dart_dev_1_9_5
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.9.4...1.9.5
> AF-1625 Release dart_dev 1.9.5

- pubspec.yaml
We will need to be able to fetch `webdriver 2.x.x` when on Dart 2.
Expand acceptable dependency range on `webdriver` to include 2.0
> Update webdriver dep for Dart 2 compatibility

- pubspec.yaml
* [Update webdriver dep for Dart 2 compatibility](https://github.com/Workiva/dart_dev/pull/271)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.9.5...Workiva:release_dart_dev_1_9_6
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.9.5...1.9.6
> AF-1872 Release dart_dev 1.9.6

- .gitignore
- README.md
- lib/api.dart
- lib/src/dart_dev_cli.dart
- lib/src/tasks/config.dart
- lib/src/tasks/dart_x_only/cli.dart
- lib/src/tasks/dart_x_only/config.dart
- lib/src/tasks/docs/cli.dart
- lib/src/tasks/examples/api.dart
- lib/src/tasks/examples/cli.dart
- lib/src/tasks/saucelabs/cli.dart
- lib/src/util.dart
- test/integration/dart_x_only_test.dart
- test/integration/generated_runner.dart
- test_fixtures/dart_x_only/pubspec.yaml
In preparation for the 2.0.0 release of dart_dev:
* Deprecate `docs` task
* Deprecate `examples` task
* Deprecate `saucelabs` task
* Add `dart1-only` conditional task
* Add `dart2-only` conditional task
* Update/add relevant documentation
@Workiva/app-frameworks
> AF-2759 V2 Prep: deprecate docs, examples, saucelabs; add dart1-only and dart2-only

- pubspec.yaml
* [clean up build](https://github.com/Workiva/dart_dev/pull/273)
* [AF-2759 V2 Prep: deprecate docs, examples, saucelabs; add dart1-only and dart2-only](https://github.com/Workiva/dart_dev/pull/275)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.9.6...Workiva:release_dart_dev_1.10.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.9.6...1.10.0
> AF-1903 Release dart_dev 1.10.0

- CHANGELOG.md
- lib/src/tasks/saucelabs/platforms.dart
There are a few additional pieces related to the `saucelabs` task that need to be deprecated in order for us to fully remove it in 2.0.0.
* Deprecate `SaucePlatform` and the constant instances of `SaucePlatform`.
* Updated `CHANGELOG.md` for this release and last release
@Workiva/app-frameworks
> AF-2776 Deprecate SaucePlatform and SaucePlatform constants

- lib/src/tasks/format/api.dart
- test/integration/format_test.dart
- test_fixtures/format/exclusions/lib/.dart_tool/main.dart
Files in `.dart_tool` were getting formatted, resulting in errors like `ProcessException: Argument list too long` since there were so many.
Add an exclude to `.dart_tool`, similar to the ones for `packages` and `.pub`
- Verify CI passes
> Don't format files in .dart_tool

- CHANGELOG.md
- pubspec.yaml
* [Don't format files in .dart_tool](https://github.com/Workiva/dart_dev/pull/283)
Requested by: @maxwell.peterson
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.0...Workiva:release_dart_dev_2.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.0...2.0.1
> AF-2823 Release dart_dev 2.0.1

- lib/src/dart_dev_cli.dart
- lib/src/tasks/test/api.dart
- test/integration/test_test.dart
If the platform is specified as `dartium` or `content-shell` while running tests under Dart 2, we should fail early instead of doing a full build.
Fail early if either platform is specified with an error message
* CI Passes
* Switch to Dart 1, publink this branch into a Dart 1 project, and verify that the test task runs as expected.
* switch to Dart 2, publink this branch into a dart 2 project, and verify that:
* `ddev test -p dartium` and `ddev test -p content-shell` fail early (before attempting a build
* `ddev test -p chrome` (or any other platform which is not `dartium` or `content-shell` runs normally.
> AF-3695: Quit test task early if dartium or content-shell on Dart 2

- lib/src/reporter.dart
Under Dart 2.1.0, when running tests that use `reporter.log`. The `quiet` variable would be null somehow and cause a runtime error in the conditional check in the `_log` method. 
I imagine this is caused by something like checked mode when running tests. I could not reproduce this runtime error when running a similar thing on the command line (prod mode).
An example failing build due to this error: https://ci.webfilings.com/build/1585120
- Don't allow these to variables to be null
- CI passes
- See passing build using this branch: https://github.com/Workiva/over_react_format/pull/25
> AF-3801 fix reporter runtime error in Dart 2.1.0

- pubspec.yaml
* [AF-3695: Quit test task early if dartium or content-shell on Dart 2](https://github.com/Workiva/dart_dev/pull/285)
* [AF-3801 fix reporter runtime error in Dart 2.1.0](https://github.com/Workiva/dart_dev/pull/287)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.1...Workiva:release_dart_dev_2.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.1...2.0.2
> AF-3464 Release dart_dev 2.0.2

- lib/src/tasks/serve/api.dart
- lib/src/tasks/test/cli.dart
- lib/src/tasks/test/config.dart
Hides all the ```pub serve``` clutter when running tests locally.
> DOC-5017 Add a flag for Disabling "pub serve" Standard Output for "dart_dev test"

- pubspec.yaml
* [DOC-5017 Add a flag for Disabling "pub serve" Standard Output for "dart_dev test"](https://github.com/Workiva/dart_dev/pull/289)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.2...Workiva:release_dart_dev_2.0.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.2...2.0.3
> AF-3803 Release dart_dev 2.0.3

- CHANGELOG.md
- lib/src/tasks/test/cli.dart
- test/integration/dart_x_only_test.dart
On Dart 2, the `test` task currently runs tests via `build_runner test`, but unfortunately this command does not exit with a non-zero exit code if the build fails, which means that the dart_dev `test` task can appear as though it passed when in fact no tests were even run.
When necessary, run `build runner build` first and fail early if it exits with a non-zero exit code. If it succeeds, then we can proceed to run the tests via `build_runner test`, knowing that they will actually run.
@maxwellpeterson-wf @smaifullerton-wk @seanburke-wf
> CPLAT-4822: Fail test task if `build_runner build` fails

- pubspec.yaml
* [CPLAT-4822: Fail test task if `build_runner build` fails](https://github.com/Workiva/dart_dev/pull/291)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.3...Workiva:release_dart_dev_2.0.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.3...2.0.4
> CPLAT-3893 Release dart_dev 2.0.4

- CHANGELOG.md
- pubspec.yaml
* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/dart_dev/pull/295)
* [CPLAT-6014 Fix Dart2 RTE](https://github.com/Workiva/dart_dev/pull/299)
* [Add test config option to delete conflicting outputs by default in Dart 2](https://github.com/Workiva/dart_dev/pull/300)
* [CPLAT-6078: Commit dart1 pubspec.lock files for all test fixtures.](https://github.com/Workiva/dart_dev/pull/301)
Requested by: @smaifullerton-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.4...Workiva:release_dart_dev_2.0.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.4...2.0.5
The logs for the request that created this PR can be found …
> CPLAT-4831 Release dart_dev 2.0.5

- CHANGELOG.md
- pubspec.yaml
* [Fix result when test task fails so that correct exit code is returned](https://github.com/Workiva/dart_dev/pull/303)
Requested by: @smaifullerton-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.5...Workiva:release_dart_dev_2.0.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.5...2.0.6
> CPLAT-6086 Release dart_dev 2.0.6

- .gitignore
- README.md
- bin/compile_sass_proxy.dart
- lib/src/dart_dev_cli.dart
- lib/src/tasks/config.dart
- lib/src/tasks/sass/api.dart
- lib/src/tasks/sass/cli.dart
- lib/src/tasks/sass/config.dart
- pubspec.yaml
- test/integration/sass_test.dart
- test/utils/sass_task_test_utils.dart
- test_fixtures/coverage/browser/pubspec.yaml
- test_fixtures/coverage/browser_needs_pub_serve/pubspec.yaml
- test_fixtures/coverage/failing_test/pubspec.yaml
- test_fixtures/coverage/functional_test/pubspec.yaml
- test_fixtures/coverage/non_test_file/pubspec.yaml
- test_fixtures/coverage/vm/pubspec.yaml
- test_fixtures/task_runner/passing_tasks/pubspec.yaml
Adds a sass task  which can be used like so:
```pub run dart_dev sass```
or
```pub run dart_dev sass --watch```
is what consumers would run locally - to compile stuff in whatever sourceDir the consumer has configured using the `expanded` output style. e.g. in wdesk_sdk’s case - in `wdesk_sdk/tool/dev.dart`, there would be:
```config.sass.sourceDir = 'lib/';```
then, in CI, consumers should run
```pub run dart_dev sass -r```
that command will run two things under the hood:
```pub run dart_dev sass --check```
and then _if that does not fail_:
```pub run dart_dev sass --outputStyle=compressed```
which will generate the minified output which will get bundled up with the pub artifact.
> CPLAT-6218 Add sass task

- lib/src/tasks/test/cli.dart
- lib/src/tasks/test/config.dart
Sometimes, consumers want to run tests on dart2js compiled code in Dart 2. This technically _can_ be done via an args separator, but this doesn't provide help info through the test task, and it also doesn't allow for a config option to be set. 
This adds a top level flag to the test task, and a config option, for running tests in release mode. 
* publink into any package consuming dart_dev
* Verify that `ddev test` runs normally on Dart 1 and Dart 2.
* Verify that `ddev test -r` and `ddev test --release` run a build via dart2js in Dart 2, and has no effect on Dart 1.
* Verify that adding a test config option in `dev.dart` to `release = true` runs tests in release mode by default.
* Verify that the command line flag takes precedent over the config option.
> CPLAT-6557: Add release flag and config option to test task

- lib/src/tasks/test/cli.dart
The `--hack-fast-builds` functionality doesn't gracefully handle test paths which start with `./`. 
Check the path and remove the preceding `./` if it exists before sending it to the runner generation.
> Remove `./` before sending test path to runner generation with hack-fast-builds flag

- CHANGELOG.md
- lib/src/dart_dev_tool.dart
- lib/src/tools/process_tool.dart
- lib/src/utils/process_declaration.dart
- lib/src/utils/start_process_and_ensure_exit.dart
- pubspec.yaml
- test/tools/process_tool_test.dart
Additions to `ProcessTool`:
- Add optional `workingDirectory` constructor param.
- Make the `Process` instance created by the tool available via a public field on `ProcessTool`.
> CPLAT-8451: Add optional `workingDirectory` param for ProcessTool.

- .travis.yml
- CHANGELOG.md
- lib/src/tools/process_tool.dart
- pubspec.yaml
- test/functional/fixtures/analyze/failure/pubspec.yaml
- test/functional/fixtures/analyze/success/pubspec.yaml
- test/tools/fixtures/format/has_dart_style/pubspec.yaml
- test/tools/fixtures/format/missing_dart_style/pubspec.yaml
- test/tools/fixtures/test/has_test_runner_and_build_test/pubspec.yaml
- test/tools/fixtures/test/has_test_runner_missing_build_test/pubspec.yaml
- test/tools/fixtures/test/missing_test_runner/pubspec.yaml
- test/tools/fixtures/tuneup_check/has_tuneup/pubspec.yaml
- test/tools/fixtures/tuneup_check/missing_tuneup/pubspec.yaml
The 3.2.0 release got created as 3.1.1. MARV should automatically use the version number in the PR from now on.
> CPLAT-8469: Fix 3.2 release. Add SDK constraints to test fixtures.

- CHANGELOG.md
- lib/src/tools/compound_tool.dart
- pubspec.yaml
When originally added, the `CompoundTool` added two newlines between the output of each individual tool. But, it's perfectly valid for compound tools to have steps that don't output anything (either all the time or conditionally), which leads to unnecessary whitespace.
This PR removes these two new-lines and replaces it with a single newline that is only printed in verbose mode. In other words, it's up to the authors of `CompoundTool`s to add extra newlines to the output as needed.
---
Also removed the deprecated `authors` field from pubspec.yaml.
> CPLAT-9175: Only log newlines in verbose mode for compound tools

- CHANGELOG.md
- doc/tools/test-tool.md
- lib/src/tools/test_tool.dart
- pubspec.yaml
- test/tools/test_tool_test.dart
The `--reporter` option is a commonly used option when running tests. This PR adds it to `TestTool` so that it can be used directly with `ddev test` instead of having to use `--test-args` to configure it.
```bash
$ ddev test --test-args="--reporter expanded"
$ ddev test --reporter expanded
```
Note: the `-r` abbreviation was intentionally **not** added because it conflicts with the abbreviation for the `--release` flag used when running tests via `build_runner`. In other words, when running tests via `ddev test`, the `-r` abbreviation has no meaning and the full option name (either `--release` or `--reporter`) should be used to avoid ambiguity.
> CPLAT-9182: Add --reporter option to TestTool

- doc/tool-composition.md
- lib/dart_dev.dart
- lib/src/tools/process_tool.dart
- lib/utils.dart
- pubspec.yaml
- test/functional.dart
- test/tools/process_tool_test.dart
We have a few consumers that start a background process before running a dev tool like tests and then need to stop that process at the end. This PR adds a `BackgroundProcessTool` to make that easier:
```dart
final testServer = BackgroundProcessTool(
'node', ['tool/server.js'],
delayAfterStart: Duration(seconds: 1));
final config = {
'test': CompoundTool()
..addTool(testServer.starter, alwaysRun: true)
..addTool(TestTool())
..addTool(testServer.stopper, alwaysRun: true),
};
```
> CPLAT-10037: Add a tool to make managing background processes easier.

- CHANGELOG.md
- lib/src/tools/test_tool.dart
- pubspec.yaml
Trying to load a deferred library with `loadLibrary()` will fail when running `ddev test --release path/to/file.dart`
Example: When deferred loading [this library](https://github.com/Workiva/doc_plat_client/blob/a5437efa719b6ed982999a32af4005e530e8966b/subpackages/text_doc_client/lib/src/embedded/text/experiences/paginated/paginated_text_experience.dart#L136) I get the following error:
```
there was a severe error DeferredLoadException: 'Loading http://localhost:61228/iVZPmn0JCIzkrO7nKP3qRcDJd2dZYG%2B3/test/unit/generated_runner_test.dart.browser_test.dart.js_18.part.js failed: Instance of 'Event'
event log:
- _loadHunk: generated_runner_test.dart.browser_test.dart.js_18.part.js
- download: generated_runner_test.dart.browser_test.dart.js_18.part.js from …
```
> Expand build filters to deal with deferred libraries

- pubspec.yaml
To unlock the latest analyzer package version, as well as the latest versions of many packages that depend on it, including build packages, we need to widen the version range for this package.
Widen version range to allow analyzer 0.41.x, the latest minor version.
No other changes were necessary
Verify locally that there are no analysis issues in this repo when using analyzer 0.41.x
Unfortunately, Dart 2.7.2 (which is what we use in CI) still can't resolve to this latest analyzer version due to SDK dependency constraints on this `build` package, so this has to be tested locally, with an SDK of at least Dart 2.9.
Also, with the constraint as-is, for some reason `pub upgrade analyzer` won't resolve the latest version, but you can force it to resolve to analyzer 0.41.x by temporarily making …
> Widen analyzer range to allow latest version (0.41.x)

- CHANGELOG.md
- pubspec.yaml
The 3.6.2 release was tagged without pubspec.yaml being updated due to direct commit not being enabled.
As a result, we have to drop that release and just do a new one: 3.6.3.
This PR also adds a changelog entry for this new release, and fixes a mistake in https://github.com/Workiva/dart_dev/pull/346 when converting from caret syntax, in which the lower bound was defined using `>` instead of `>=`.
> Release with direct-commit enabled, fix constraint, add changelog

- CHANGELOG.md
- pubspec.yaml
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.6.3...Workiva:release_dart_dev_3.6.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.6.3...3.6.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?pull_number=349&repo_name=Workiva%2Fdart_dev)
> Release dart_dev 3.6.4

- .github/workflows/dart_ci.yml
- Dockerfile
- pubspec.yaml
- test/functional/documentation_test.dart
- test/functional/fixtures/analyze/failure/pubspec.yaml
- test/functional/fixtures/analyze/success/pubspec.yaml
- test/tools/fixtures/format/has_dart_style/pubspec.yaml
- test/tools/fixtures/format/missing_dart_style/pubspec.yaml
- test/tools/fixtures/test/has_test_runner_and_build_test/pubspec.yaml
- test/tools/fixtures/test/has_test_runner_missing_build_test/pubspec.yaml
- test/tools/fixtures/test/missing_test_runner/pubspec.yaml
- test/tools/fixtures/tuneup_check/has_tuneup/pubspec.yaml
- test/tools/fixtures/tuneup_check/missing_tuneup/pubspec.yaml
In order for projects to be compatible with Dart 2.13, there are dependencies that need to have their ranges widened. 
For a list of dependencies expected to be changed, see the dependencies section of the Dart 2.12+ [wiki page](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=189370832).
Another necessary change is the removal of `build_vm_compilers`. If this is the case, additional clean up may need to be done, such as removing the associated config from `build.yaml` or updating how tests are run. A member of Client Platform will be following up with PRs that have CI failures to resolve any issues or perform necessary clean up.
For any questions or concerns, don't hesitate to reach us in the #support-client-plat Slack channel!
- Update specific dependencies to be compatible …
> Widen Dependency Ranges Blocking Dart 2.13

- CHANGELOG.md
- pubspec.yaml
* [Use Github actions for CI (Bye Travis 👋)](https://github.com/Workiva/dart_dev/pull/348)
* [DE-630: Delete docs.yaml file for Workiva/dart_dev](https://github.com/Workiva/dart_dev/pull/350)
* [Widen Dependency Ranges Blocking Dart 2.13](https://github.com/Workiva/dart_dev/pull/352)
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.6.4...Workiva:release_dart_dev_3.6.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.6.4...3.6.5
This pull request can be recreated by clicking …
> RM-94762 Release dart_dev 3.6.5

- CHANGELOG.md
- lib/src/tools/test_tool.dart
- test/tools/fixtures/test/has_test_runner_and_build_test/pubspec.yaml
- test/tools/fixtures/test/has_test_runner_missing_build_test/pubspec.yaml
- test/tools/fixtures/test/missing_test_runner/pubspec.yaml
- test/tools/test_tool_test.dart
Now only uses `build_runner` to run tests if the package has a direct dependency on both `build_runner` and `build_test` (previously we only checked for `build_test`). For packages that contain builder implementations, they will likely have a dependency on `build_test` for use in their builder tests, but don't need to run tests via `build_runner`.
> CPLAT-15446: Improve criteria for using `build_runner` for tests

- pubspec.yaml
* [CPLAT-15446: Improve criteria for using `build_runner` for tests](https://github.com/Workiva/dart_dev/pull/354)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.6.5...Workiva:release_dart_dev_3.6.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.6.5...3.6.6
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?pull_number=355&repo_name=Workiva%2Fdart_dev)
> RM-110307 Release dart_dev 3.6.6

- .github/workflows/dart_ci.yml
- CHANGELOG.md
- Dockerfile
Currently we treat Dart 2.7.2 as our primary SDK target when running CI. At Workiva, we're transitioning to Dart 2.13.4 as our primary version for development. Perhaps we should treat it as our primary target in CI.
- Updated Dockerfile to use the google/dart:2.13.4 image.
- Updated dart_ci.yaml to explicitly run on Dart 2.13.4 and make sure we're checking formatting on that version of the SDK.
- I left 2.7.2 in the test matrix since we technically still support older versions of Dart.
> Treat Dart 2.13.4 as the primary SDK version for dev and CI

- pubspec.yaml
* [Treat Dart 2.13.4 as the primary SDK version for dev and CI](https://github.com/Workiva/dart_dev/pull/356)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.6.6...Workiva:release_dart_dev_3.6.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.6.6...3.6.7
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?pull_number=357&repo_name=Workiva%2Fdart_dev)
> RM-114253 Release dart_dev 3.6.7

- CHANGELOG.md
- lib/utils.dart
dart_dev has some fine ArgResults utilities that are useful for authors of new dart_dev tools.
Added an export for `src/utils/arg_results_utils.dart`.
> Export the ArgResults utils

- README.md
- doc/tools/test-tool.md
- doc/tools/tuneup-check-tool.md
- doc/tools/webdev-serve-tool.md
- lib/src/tools/analyze_tool.dart
- lib/src/tools/format_tool.dart
- lib/src/tools/over_react_format_tool.dart
- lib/src/tools/test_tool.dart
- lib/src/tools/tuneup_check_tool.dart
- lib/src/tools/webdev_serve_tool.dart
- lib/src/utils/format_tool_builder.dart
- lib/src/utils/global_package_is_active_and_compatible.dart
- lib/src/utils/run_process_and_ensure_exit.dart
- pubspec.yaml
- test/functional.dart
- test/functional/documentation_test.dart
- test/tools/analyze_tool_test.dart
- test/tools/format_tool_test.dart
- test/tools/test_tool_test.dart
- test/tools/tuneup_check_tool_test.dart
- test/tools/webdev_serve_tool_test.dart
- test/utils.dart
- test/utils/format_tool_builder_test.dart
- tool/dart_dev/config.dart
Purpose:
ddev analyze runs dartanalyzer, which does not leverage the analysis server
ddev format may run dartfmt (unless the package depends on dart_style)
in several places, ddev will run other dart executables via pub run
As of Dart 2.10 (https://medium.com/dartlang/announcing-dart-2-10-350823952bd5), there exists a new unified dart CLI with improved options for analysis, formatting, and running packages. The primary benefit to this new CLI is dart analyze which (like tuneup) uses the analysis server, which is important because the now-outdated dartanalyzer suffers from several deficiences and bugs because it doesn't use the analysis server.
Note: dart_dev also provides a tuneup-based option for analysis. There does still seem to be some functionality in tuneup that doesn't exist in …
> CPLAT-15507: ddev should use new dart CLI

- CHANGELOG.md
- lib/src/tools/compound_tool.dart
- lib/src/tools/function_tool.dart
- lib/src/tools/test_tool.dart
- lib/src/utils/rest_args_with_separator.dart
- test/tools/function_tool_test.dart
- test/tools/test_tool_test.dart
- test/utils/rest_args_with_separator_test.dart
- Update `TestTool` to allow arguments after a separator (`--`). These arguments will always be passed to the `dart test` process. The main use case for this is integration with IDE plugins that enable running tests directly from the IDE.
- Update `FunctionTool` to allow arguments after a separator (`--`). There isn't a strong reason to disallow this since the function tool could do anything it wants with those args (and now we have a concrete use case for just that).
- Fix a bug in `takeAllArgs` (the arg mapper util used with `CompoundTool`) so that it now properly restores the first separator (`--`) if present in the original arguments list.
> CPLAT-16476 Allow args after separator to TestTool

- CHANGELOG.md
- Dockerfile
This Sourcegraph batch replaces deprecated commands from the Dart SDK with the new ones.
All new CLI commands now live under the main `dart` executable. See this issue for the details
https://github.com/dart-lang/sdk/issues/46100
This PR might need to be checked or tweaked for possible errors in the arguments to 
`dart analyze` and `dart format` since they take slightly different arguments than the original.
In most cases for analyze all the arguments can be removed and it can just be `dart analyze`.
Some of the argument changes were difficult to match and replace in an automated way. Since
there are only a few places that might break, it'll be easier to let the batch create the PR
and then manually adjust them.
`-w` should be removed automatically since overwriting files is now the …
> Replace deprecated commands with new dart commands

- pubspec.yaml
When we previously upgraded some dependencies, we raised the minimum just a bit too far for build_runner, io, and pubspec_parse. By lowering these slightly (which is safe to do given our usage), it allows us to resolve to analyzer v1 in wdesk_sdk sooner.
> Widen build_runner, io, and pubspec_parse ranges

- CHANGELOG.md
- pubspec.yaml
Widen analyzer range to allow v2. Compatibility with V2 is tested here: https://github.com/Workiva/dart_dev/pull/376
> FEA-427: Widen analyzer range to allow v2

- CHANGELOG.md
- skynet.yaml
Currently release pipelines are failing because they require a skynet run in order to pass the testing phase of the pipeline. We would like to not have to manually check that the github workflow passed and override the pipeline so we need a way to automatically check that the workflow passed and tell the pipeline that all is good.
Add a skynet.yaml that checks the github workflow run and passes or fails the skynet run depending on the results.
Add skynet run to check that the github workflow run passes
> FW-144 Add skynet config that verifies that github workflow passes

- test/functional/documentation_test.dart
A newer version of the Dart SDK has removed `dartanalyzer`, so we need to update our docs tests to use `dart analyze`.
> Update docs tests to use `dart analyze`

- .github/workflows/dart_ci.yml
- lib/src/executable.dart
- lib/src/tools/analyze_tool.dart
- lib/src/tools/format_tool.dart
- lib/src/tools/over_react_format_tool.dart
- lib/src/tools/test_tool.dart
- lib/src/tools/tuneup_check_tool.dart
- lib/src/tools/webdev_serve_tool.dart
- lib/src/utils/dart_dev_paths.dart
- lib/src/utils/dart_tool_cache.dart
- lib/src/utils/executables.dart
- lib/src/utils/global_package_is_active_and_compatible.dart
- test/functional.dart
- test/functional/documentation_test.dart
- test/tools/analyze_tool_test.dart
- test/tools/format_tool_test.dart
- test/tools/test_tool_test.dart
- test/tools/tuneup_check_tool_test.dart
- test/tools/webdev_serve_tool_test.dart
- test/utils.dart
- test/utils/dart_dev_paths_test.dart
There are several paths that we're using in our executable and in the run script that we generate and we need to construct them with the appropriate APIs from `package:path` to ensure they work when running on Windows. This PR does that.
> Fixes for Windows compatibility

- lib/src/executable.dart
- lib/src/tools/analyze_tool.dart
- lib/src/tools/format_tool.dart
- lib/src/tools/over_react_format_tool.dart
- lib/src/tools/test_tool.dart
- lib/src/tools/tuneup_check_tool.dart
- lib/src/tools/webdev_serve_tool.dart
- lib/src/utils/dart_dev_paths.dart
- lib/src/utils/dart_tool_cache.dart
- lib/src/utils/executables.dart
- lib/src/utils/global_package_is_active_and_compatible.dart
- test/utils/dart_dev_paths_test.dart
There are several paths that we're using in our executable and in the run script that we generate and we need to construct them with the appropriate APIs from `package:path` to ensure they work when running on Windows. This PR does that.
> Fixes for Windows compatibility (backpatch to 3.7.x)

- .github/dependabot.yml
Ignore major version bumps for all packages
> dependabot: ignore majors

- .github/workflows/dart_ci.yml
- .pubignore
- CHANGELOG.md
- lib/src/tools/analyze_tool.dart
- lib/src/tools/format_tool.dart
- lib/src/utils/dart_semver_version.dart
- pubspec.yaml
- test/functional.dart
- Automatically use `dart analyze` instead of `dartanalyzer` when on Dart SDK v2.18 or higher (`dartanalyzer` was removed in this version).
- Automatically use `dart format` instead of `dartfmt` when on Dart SDK v2.15 or higher (`dartfmt` was removed in this version).
> Auto-switch analyze and format commands when on certain Dart SDKs

- .github/workflows/dart_ci.yml
- CHANGELOG.md
- analysis_options.yaml
- lib/src/events.dart
- lib/src/executable.dart
- lib/src/tools/analyze_tool.dart
- lib/src/tools/compound_tool.dart
- lib/src/tools/format_tool.dart
- lib/src/tools/process_tool.dart
- lib/src/tools/test_tool.dart
- lib/src/tools/webdev_serve_tool.dart
- lib/src/utils/assert_no_positional_args_before_separator.dart
- lib/src/utils/logging.dart
- lib/src/utils/organize_directives/namespace_collector.dart
- lib/src/utils/organize_directives/organize_directives.dart
- lib/src/utils/organize_directives/organize_directives_in_paths.dart
- pubspec.yaml
- test/functional/format_tool_functional_test.dart
- test/tools/analyze_tool_test.dart
- test/tools/compound_tool_test.dart
- test/tools/format_tool_test.dart
- test/tools/process_tool_test.dart
- test/tools/shared_tool_tests.dart
- test/tools/test_tool_test.dart
- test/tools/webdev_serve_tool_test.dart
- test/utils/format_tool_builder_test.dart
- Address new lints on 2.18
- Run formatter on 2.18
- Replace deprecated pedantic package with lints package
- Tweaks to CI
> FEDX-13: Dart 2.18 lints & formatting

- pubspec.yaml
- test/tools/fixtures/format/has_dart_style/pubspec.yaml
Summary
---
Frontend Frameworks is updating dependencies! Now that we can resolve to analyzer 2
we can raise the minimums of many dependencies were ranged to support both 
analyzer 1 and 2.
```
pubspec_codemod raise-min analyzer 2.0.0 --recursive
pubspec_codemod raise-min dependency_validator 3.0.0 --recursive
pubspec_codemod raise-min test_html_builder 3.0.0 --recursive
pubspec_codemod raise-min dart_style 2.0.0 --recursive
pubspec_codemod raise-min build_web_compilers 3.0.0 --recursive
pubspec_codemod raise-min build_test 2.0.0 --recursive
pubspec_codemod raise-min build_runner 2.0.0 --recursive
pubspec_codemod raise-min w_common 3.0.0 --recursive
pubspec_codemod raise-min w_common_tools 3.0.0 --recursive
pubspec_codemod raise-min uuid 3.0.0 --recursive
pubspec_codemod raise-min fluri …
```
> Update dev dependencies for analyzer 2

- CHANGELOG.md
- lib/src/executable.dart
When we migrated this package to null-safe, we missed some logic in our run script generation that would include a Dart language comment to set the language version to 2.9 by default. This prevents the null-safe dart_dev from being able to run on Dart 3 where null-safety is required.
Remove this logic as it's no longer needed. We'll still copy over a language comment from `tool/dart_dev/config.dart` if one exists, otherwise we omit it which will allow dart_dev to run on Dart 3.
> FEDX-518 Now that dart_dev itself is null-safe, it should be able to generate a null-safe run script

- lib/src/executable.dart
- lib/src/tools/format_tool.dart
- test/tools/format_tool_test.dart
We can save a lot (~90%) of execution time of `dart_dev format` on some repos with two changes:
- Not recursing into directories that are a priori excluded from the formatter's list (e.g., hidden directories like .git). Note that this means we no longer build and log a comprehensive list of excluded files. I think it's worth it to run so much faster.
- Removing the `collapseDirectories` feature, to be replaced with batch parallel invocations. Computing the collapsible directories was some kind of superlinear deduplication. This could maybe be optimized in a way that would allow it to remain, but it seems it was intended as a stopgap solution for argv limitations in the first place.
This is technically a breaking change to the API since we no longer return a full list of excluded files and …
> format_tool: optimization pass

- CHANGELOG.md
- lib/src/dart_dev_runner.dart
- lib/src/executable.dart
- lib/src/tools/clean_tool.dart
- lib/src/utils/dart_dev_paths.dart
- lib/src/utils/parse_imports.dart
- lib/src/utils/pubspec_lock.dart
- pubspec.yaml
- test/utils/parse_imports_test.dart
This PR adapted from a 2021 PR by @evanweible-wf: https://github.com/Workiva/dart_dev/pull/363. See that PR for discussion and performance metrics.
My changes:
- Merge conflicts resolved.
- Most code review comments addressed.
- Misc cleanup and rearrangement to bring this branch in line with since-merged refactors (most notably the refactor of path usage performed in https://github.com/Workiva/dart_dev/pull/386; specifically 1ad8316217a1e2762fc32e1ca2abb60eb4e49e5d).
Functionality changes described below.
---
After compilation, the startup time for subsequent `dart run dart_dev` commands should be significantly improved.
This compiled exectuable is cached in `.dart_tool/dart_dev/` along with a digest that is used to determine when recompilation is needed.
Packages with …
> Compile the `dart_dev` run script for better performance

- LICENSE
- NOTICE
- Use the full Apache 2.0 license text in the LICENSE file so that it is properly detected by automated tools like the pub.dev registry
- The attributions have been moved to the NOTICE file
> FEDX-1094: Use full Apache 2.0 license text; move attributions to NOTICE

- CHANGELOG.md
- pubspec.yaml
* Minor changes:
* [Compile the `dart_dev` run script for better performance](https://github.com/Workiva/dart_dev/pull/426)
* [Minor pubspec and readme cleanup](https://github.com/Workiva/dart_dev/pull/411)
* [FEDX-684 Finish GHA](https://github.com/Workiva/dart_dev/pull/427)
* [FEDX-1094: Use full Apache 2.0 license text; move attributions to NOTICE](https://github.com/Workiva/dart_dev/pull/429)
* [fedx_codeowners_file](https://github.com/Workiva/dart_dev/pull/430)
* [Upgrade deps for Dart 3](https://github.com/Workiva/dart_dev/pull/432)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/4.1.1...Workiva:release_dart_dev_4.2.0
Diff Between Last Tag and New Tag: …
> RM-242322 Release dart_dev 4.2.0

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yaml
Implements gha-dart-oss for publish and other stuff
Notably checks and tests are not implemented because gha-dart-oss wont correctly use dart_dev to run analysis within dart_dev itself
> FEDX-1595: implemented gha-dart-oss publish

- lib/src/tools/over_react_format_tool.dart
- lib/src/utils/format_tool_builder.dart
The `hackFastFormat` command is used by some of our dev tooling like IDE auto-formatting and precommit hooks. It does not currently support organizing directives, whereas the full `format` command does.
This PR updates `hackFastFormat` to check the project's ddev config to see if it has enabled `organizeDirectives`, and if so, it ensures that the format tool it sets up matches that configuration. In other words, `hackFastFormat` should now respect the `organizeDirectives` configuration of the project it is running in, which should allow IDE auto-formatting and precommit hooks that use `hackFastFormat` to match behavior of running `ddev format`.
> FEDX-1727: Support `organizeDirectives` config via `hackFastFormat`

- CHANGELOG.md
- pubspec.yaml
* [FEDX-1595: implemented gha-dart-oss publish](https://github.com/Workiva/dart_dev/pull/434)
* [FEDX-1727: Support `organizeDirectives` config via `hackFastFormat`](https://github.com/Workiva/dart_dev/pull/438)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/4.2.0...Workiva:release_dart_dev_4.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/4.2.0...4.2.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?rep …
> RM-281924 Release dart_dev 4.2.1

- lib/src/tools/webdev_serve_tool.dart
- test/tools/webdev_serve_tool_test.dart
When running dart run dart_dev serve under Dart 3, it checks that webdev is installed, but it insists on webdev ^2.0.0. Dor Dart 3, only webdev ^3.0.0 resolves. 
Switch the version to check for based on the version of Dart being run. For Dart 2, use ^2.0.0 and Dart 3 use ^3.0.0 of webdev.
> Fix webdev version check for Dart 3

- CHANGELOG.md
- pubspec.yaml
* [Fix webdev version check for Dart 3](https://github.com/Workiva/dart_dev/pull/442)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/4.2.1...Workiva:release_dart_dev_4.2.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/4.2.1...4.2.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?repo_name=Workiva%2Fdart_dev&pull_number=443)
> RM-291603 Release dart_dev 4.2.2

- lib/src/utils/organize_directives/organize_directives.dart
- test/tools/fixtures/organize_directives/directives.dart
- test/utils/organize_imports/organize_directives_test.dart
An issue with `organizeDirectives` and the `// @dart=2.11` comment was discovered:
Given the following input:
```dart
// @dart=2.11
import 'package:c_package/c_package.dart';
import 'package:a_package/a_package.dart';
```
The result would be
```dart
import 'package:a_package/a_package.dart';
// @dart=2.11
import 'package:c_package/c_package.dart';
```
This is a problem as the `// @dart=2.11` header _must_ be at the top of the file
When `organizeDirectives` runs, it tries to figure out what comments are linked with which directives. It does this using each token's `precedingComments`, which essentially just selects all whitespace/comments before a line
When the above example is ran, the `// @dart=2.11` comment is considered apart of `c_package` and moved along with it
This pr simply …
> FEDX-1952: Fixed bug with organizeDirectives and LanguageVersion comment

- lib/src/tools/compound_tool.dart
The `args` package just released [2.7.0](https://pub.dev/packages/args/changelog#270), which adds an optional param in `ArgParser.flag`.
> Added option hideNegatedUsage to ArgParser.flag() allowing a flag to be negatable without showing it in the usage text.
This breaks dart_dev's override of this method, resulting in the following errors when attempting to analyze or run dart_dev code:
```
lib/src/tools/compound_tool.dart:262:8: Error: The method 'CompoundArgParser.addFlag' has fewer named arguments than those of overridden method 'ArgParser.addFlag'.
void addFlag(String name,
^
/C:/Users/runneradmin/.pub-cache/hosted/pub.dev/args-2.7.0/lib/src/arg_parser.dart:134:8: Context: This is the overridden method ('addFlag').
void addFlag(String name,
^
lib/src/tools/compound_tool.dart:262:8: …
```
> Work around invalid override error when args 2.7.0 is pulled in (Dart 3.3+ only issue)

- CHANGELOG.md
- pubspec.yaml
* [Bump lints from 4.0.0 to 5.0.0 in the major group](https://github.com/Workiva/dart_dev/pull/439)
* [Bump Workiva/gha-dart-oss from 0.1.5 to 0.1.7 in the gha group across 1 directory](https://github.com/Workiva/dart_dev/pull/441)
* [FEDX-1952: Fixed bug with organizeDirectives and LanguageVersion comment](https://github.com/Workiva/dart_dev/pull/444)
* [Work around invalid override error when args 2.7.0 is pulled in (Dart 3.3+ only issue)](https://github.com/Workiva/dart_dev/pull/448)
Requested by: @matthewnitschke-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/4.2.2...Workiva:release_dart_dev_4.2.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/4.2.2...4.2.3 …
> RM-295281 Release dart_dev 4.2.3
