pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-844
CP-827  - Add line-length option to format task.  - https://github.com/Workiva/dart_dev/pull/18
CP-822  - CLI improvements & cleanup.  - https://github.com/Workiva/dart_dev/pull/13
CP-823  - Integration Tests, darv_dev  - https://github.com/Workiva/dart_dev/pull/15
CP-841  - Add a CHANGELOG, dart_dev  - https://github.com/Workiva/dart_dev/pull/28
CP-843  - New Task: Copy License  - https://github.com/Workiva/dart_dev/pull/16
CP-808  - dart_dev initial implementation  - https://github.com/Workiva/dart_dev/pull/3
CP-849  - Add Apache 2.0 license, dart_dev  - https://github.com/Workiva/dart_dev/pull/19
CP-839  - New Task: Code Coverage  - https://github.com/Workiva/dart_dev/pull/25
CP-842  - Ready …

CP-844 Release dart_dev 1.0.0

---

README.md

#31 
Added pub badge to readme.
n/a
n/a
@jayudey-wf

CP-917 Add pub badge to readme.

---

CHANGELOG.md

Update `CHANGELOG.md` for 1.0.2 release.
n/a
n/a
@jayudey-wf

CP-1071 Update CHANGELOG.md 1.0.2

---

pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1072
CP-1070  - Format: allow exclusions  - https://github.com/Workiva/dart_dev/pull/81
CP-1063  - Running coverage on non_test dart files  - https://github.com/Workiva/dart_dev/pull/78
CP-1069  - Copy License: trim leading/trailing empty lines  - https://github.com/Workiva/dart_dev/pull/80
CP-1071  - Update CHANGELOG.md 1.0.2  - https://github.com/Workiva/dart_dev/pull/82
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.1...CP-1072_release_1.0.2

CP-1072 Release dart_dev 1.0.2

---

pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1073
CP-1081  - Update README with warning about supported platforms on CI servers.  - https://github.com/Workiva/dart_dev/pull/84
CP-1091  - Allow individual test files  - https://github.com/Workiva/dart_dev/pull/85
CP-1102  - Upgrade dartdoc dependency range  - https://github.com/Workiva/dart_dev/pull/90
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.2...CP-1073_release_1.0.3

CP-1073 Release dart_dev 1.0.3

---

pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1108
CP-1124  - Fix browser file detection (dart2js output changed)  - https://github.com/Workiva/dart_dev/pull/98
CP-1125  - Fix incorrect grammer in format task output  - https://github.com/Workiva/dart_dev/pull/97
CP-1122  - Bash completions  - https://github.com/Workiva/dart_dev/pull/96
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.3...CP-1108_release_1.0.4

CP-1108 Release dart_dev 1.0.4

---

README.md

- broken link in README (docs only change)
**Source:**
- none
**Tests:**
- none
- none
- strong mode link in readme works and looks right
@evanweible-wf
@jayudey-wf

CP-1212 Update README.md for broken link

---

README.md

- add docs badge
**Source:**
- none
**Tests:**
- none
- none
- none
@evanweible-wf
@jayudey-wf

CP-1225 add docs badge, dart_dev

---

pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1209
CP-1212  - Update README.md for broken link  - https://github.com/Workiva/dart_dev/pull/118
CP-1225  - add docs badge, dart_dev  - https://github.com/Workiva/dart_dev/pull/119
CP-1303 Fail coverage task if a unit tests fails  - https://github.com/Workiva/dart_dev/pull/125
CP-1318  - Add ability to pass in test name as a parameter to test task  - https://github.com/Workiva/dart_dev/pull/126
CP-1334  - copy-license: catch FSE when reading non-utf8 file  - https://github.com/Workiva/dart_dev/pull/129
CP-1393  - Update test task to observe `--no-unit` flag  - https://github.com/Workiva/dart_dev/pull/131
Diff Between Last Tag and Proposed Release: …

CP-1209 Release dart_dev 1.1.0

---

CHANGELOG.md

**Docs only change.**
Updated changelog: https://github.com/Workiva/dart_dev/blob/changelog/CHANGELOG.md
@jayudey-wf

CP-1399 Update changelog for 1.1.0 and 1.1.1

---

pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1397
CP-1398  - Update logic around including unit tests by default  - https://github.com/Workiva/dart_dev/pull/134
CP-1399  - Update changelog for 1.1.0 and 1.1.1  - https://github.com/Workiva/dart_dev/pull/135
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.1.0...CP-1397_release_1.1.1

CP-1397 Release dart_dev 1.1.1

---

test/integration/coverage_test.dart

- Tests were intermittently timing out during a part of the CI
**Source:**
- Extended timeout
**Tests:**
- n/a
- n/a
- Passing CI
@evanweible-wf

CP-1524 Coverage tests were routinely timing out on travis.ci

---

pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1941
======= dart_dev 1.4.0 items =======
REF-956  - Add --check option to dart_dev gen-test-runner  - https://github.com/Workiva/dart_dev/pull/163
======= end =======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.3.0...CP-1941_release_1.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.3.0...1.4.0

CP-1941 Release dart_dev 1.4.0

---

pubspec.yaml

nudge version

---

lib/src/tasks/test/cli.dart
lib/src/tasks/test/config.dart

Fixes #120 
Looking for some initial feedback regarding approach, etc.
FYI @greglittlefield-wf @patkujawa-wf

CP-2124: Add Debug Flag to Test Task

---

pubspec.yaml

* [CP-2124: Add Debug Flag to Test Task](https://github.com/Workiva/dart_dev/pull/195)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.3...version-bump-dart_dev-1-5-4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.3...1.5.4

CP-3178 Release dart_dev 1.5.4

---

pubspec.yaml

* [Add additional configuration options to functional coverage / test task](https://github.com/Workiva/dart_dev/pull/201)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.4...version-bump-dart_dev-1-6-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.4...1.6.0

CP-3316 Release dart_dev 1.6.0

---

pubspec.yaml

* [HY-4464 - Add onError handlers to Reporter](https://github.com/Workiva/dart_dev/pull/209)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.0...version-bump-dart_dev-1-7-1_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.0...1.7.1

CP-3342 Release dart_dev 1.7.1

---

docs.yml

We would like this readme in the dev portal
Added docs.yml
previous major version
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
@Workiva/devtools-pp

WP-3669 : added docs.yml

---

lib/src/tasks/task_runner/api.dart
lib/src/tasks/task_runner/cli.dart
test/integration/task_runner_test.dart
test_fixtures/coverage/functional_test/pubspec.yaml
test_fixtures/task_runner/failing_tasks/test/simple_test.dart

- The task-runner task could use a little bit of updating based on feedback. https://github.com/Workiva/dart_dev/issues/208
**Source:**
- Report task output upon individual task completion
- Include stdout and stderr when a task fails
- Fail task-runner if one of the tasks failed and provide output
**Tests:**
- added
- task-runner
- passing CI
- install into project and verify that task runner is working as expected
@Workiva/web-platform-pp 
@todbachman-wf

WP-4112 Updating task-runner task based on feedback

---

pubspec.yaml

* [WP-4112 Updating task-runner task based on feedback](https://github.com/Workiva/dart_dev/pull/215)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.3...version-bump-dart_dev-1-7-4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.3...1.7.4

WP-3887 Release dart_dev 1.7.4

---

pubspec.yaml

* [UIP-2338 / CP-2144: Support custom local format task + specifying files via CLI](https://github.com/Workiva/dart_dev/pull/222)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.5...version-bump-dart_dev-1-7-6
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.5...1.7.6

WP-4267 Release dart_dev 1.7.6

---

CODEOWNERS

Add a `CODEOWNERS` file so that we can turn on the "require reviews from codeowners" option.
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
@Workiva/app-frameworks

WP-5640 Add CODEOWNERS file

---

pubspec.yaml

* [WP-5640 Add CODEOWNERS file](https://github.com/Workiva/dart_dev/pull/246)
* [WP-6076 widen rxdart dependency range](https://github.com/Workiva/dart_dev/pull/250)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...Workiva:release_dart_dev_1_9_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...1.9.1

WP-5547 Release dart_dev 1.9.1

---

pubspec.yaml

* [Add docstrings to coverage config](https://github.com/Workiva/dart_dev/pull/233)
* [WP-6444 Dart2 and DDC compatibility](https://github.com/Workiva/dart_dev/pull/254)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...Workiva:release_dart_dev_1_9_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.0-alpha...1.9.2

WP-6083 Release dart_dev 1.9.2

---

.travis.yml
pubspec.yaml
test_fixtures/coverage/functional_test/pubspec.yaml

Pretty self-explanatory.
@Workiva/app-frameworks

Use dependency_validator

---

pubspec.yaml

* [AF-1586 Add assertCheckedModeEnabled() utility.](https://github.com/Workiva/dart_dev/pull/265)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.9.3...Workiva:release_dart_dev_1_9_4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.9.3...1.9.4

AF-1608 Release dart_dev 1.9.4

---

pubspec.yaml

* [AF-2776 Deprecate SaucePlatform and SaucePlatform constants](https://github.com/Workiva/dart_dev/pull/277)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.10.0...Workiva:release_dart_dev_1.10.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.10.0...1.10.1

AF-2766 Release dart_dev 1.10.1

---

CHANGELOG.md
pubspec.yaml

* [AF-2760 Dart2 compatibility](https://github.com/Workiva/dart_dev/pull/274)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.10.1...Workiva:release_dart_dev_2.0.0-beta
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.10.1...2.0.0-beta

AF-2777 Release dart_dev 2.0.0-beta

---

pubspec.yaml

* [CPLAT-6218 Add sass task](https://github.com/Workiva/dart_dev/pull/305)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.0.6...Workiva:release_dart_dev_2.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.0.6...2.1.0

RM-53261 Release dart_dev 2.1.0

---

pubspec.yaml

* [CPLAT-6557: Add release flag and config option to test task](https://github.com/Workiva/dart_dev/pull/308)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.1.0...Workiva:release_dart_dev_2.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.1.0...2.2.0

RM-53550 Release dart_dev 2.2.0

---

pubspec.yaml

* [Gen test runner in test task](https://github.com/Workiva/dart_dev/pull/315)
Requested by: @corwinsheahan-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.2.0...Workiva:release_dart_dev_2.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.2.0...2.2.1

RM-54980 Release dart_dev 2.2.1

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/2.2.1...Workiva:release_dart_dev_3.0.0-alpha.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/2.2.1...3.0.0-alpha.0

RM-59180 Release dart_dev 3.0.0-alpha.0

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.0.0-alpha.0...Workiva:release_dart_dev_3.0.0-alpha.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.0.0-alpha.0...3.0.0-alpha.1

RM-59519 Release dart_dev 3.0.0-alpha.1

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.0.0-alpha.1...Workiva:release_dart_dev_3.0.0-alpha.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.0.0-alpha.1...3.0.0-alpha.2

RM-60080 Release dart_dev 3.0.0-alpha.2

---

pubspec.yaml

* [CPLAT-4521 CPLAT-7627 CPLAT-7708 dart_dev v3.0.0](https://github.com/Workiva/dart_dev/pull/318)
* [Remove `./` before sending test path to runner generation with hack-fast-builds flag](https://github.com/Workiva/dart_dev/pull/326)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.0.0-alpha.2...Workiva:release_dart_dev_3.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.0.0-alpha.2...3.0.0

RM-58689 Release dart_dev 3.0.0

---

CHANGELOG.md
pubspec.yaml

Changelog and version bump for v3.4.0

---

pubspec.yaml

* [Export the ArgResults utils](https://github.com/Workiva/dart_dev/pull/360)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.6.7...Workiva:release_dart_dev_3.7.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.6.7...3.7.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?pull_number=361&repo_name=Workiva%2Fdart_dev)

RM-114830 Release dart_dev 3.7.0

---

pubspec.yaml

* [Add import sorting to format tool (backpatch to v3.7.1)](https://github.com/Workiva/dart_dev/pull/381)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.8.7...Workiva:release_dart_dev_3.7.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.8.7...3.7.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?pull_number=383&repo_name=Workiva%2Fdart_dev)

RM-126419 Release dart_dev 3.7.2

---

CHANGELOG.md
pubspec.yaml

* [Fixes for Windows compatibility (backpatch to 3.7.x)](https://github.com/Workiva/dart_dev/pull/387)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.9.0...Workiva:release_dart_dev_3.7.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.9.0...3.7.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?repo_name=Workiva%2Fdart_dev&pull_number=388)

RM-158384 Release dart_dev 3.7.3

---

CHANGELOG.md
pubspec.yaml

* [Fixes for Windows compatibility](https://github.com/Workiva/dart_dev/pull/386)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.9.0...Workiva:release_dart_dev_3.9.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.9.0...3.9.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?repo_name=Workiva%2Fdart_dev&pull_number=389)

RM-154451 Release dart_dev 3.9.1

---

lib/src/tools/analyze_tool.dart
lib/src/tools/format_tool.dart
pubspec.yaml
test/functional/documentation_test.dart

Prepare to upgrade glob
Add `import 'package:glob/list_local_fs.dart';` to avoid breaking changes in glob
Widen the glob range since breaking changes are addressed

Widen glob

---

CHANGELOG.md
pubspec.yaml

* [Widen glob](https://github.com/Workiva/dart_dev/pull/393)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.9.1...Workiva:release_dart_dev_3.7.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.9.1...3.7.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?repo_name=Workiva%2Fdart_dev&pull_number=394)

RM-165659 Release dart_dev 3.7.4

---

pubspec.yaml

* [Create dependabot.yml](https://github.com/Workiva/dart_dev/pull/390)
* [dependabot: ignore majors](https://github.com/Workiva/dart_dev/pull/392)
* [Auto-switch analyze and format commands when on certain Dart SDKs](https://github.com/Workiva/dart_dev/pull/398)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.7.4...Workiva:release_dart_dev_3.9.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.7.4...3.9.2
This pull request can be recreated by clicking …

RM-158390 Release dart_dev 3.9.2

---

pubspec.yaml

* Major changes:
* [Migrate to null safety](https://github.com/Workiva/dart_dev/pull/402)
* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/dart_dev/pull/400)
* [FEDX-13: Dart 2.18 lints & formatting](https://github.com/Workiva/dart_dev/pull/401)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/3.9.2...Workiva:release_dart_dev_4.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/3.9.2...4.0.0
This pull request can be recreated by clicking …

RM-178586 Release dart_dev 4.0.0

---

pubspec.yaml

* [Update dev dependencies for analyzer 2](https://github.com/Workiva/dart_dev/pull/412)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/4.0.1...Workiva:release_dart_dev_4.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/4.0.1...4.0.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?repo_name=Workiva%2Fdart_dev&pull_number=413)

RM-198189 Release dart_dev 4.0.2

---

pubspec.yaml

* [Dart 2.19](https://github.com/Workiva/dart_dev/pull/416)
* [FEDX-518 Now that dart_dev itself is null-safe, it should be able to generate a null-safe run script](https://github.com/Workiva/dart_dev/pull/420)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/4.0.2...Workiva:release_dart_dev_4.0.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/4.0.2...4.0.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?repo …

RM-211323 Release dart_dev 4.0.3

---

pubspec.yaml

* Minor changes:
* [FEDX-519 Raise maximum SDK to include Dart 3 and update CI](https://github.com/Workiva/dart_dev/pull/422)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/4.0.3...Workiva:release_dart_dev_4.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/4.0.3...4.1.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6691996821356544/?repo_name=Workiva%2Fdart_dev&pull_number=423)

RM-223351 Release dart_dev 4.1.0
